/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import model.House;
import java.awt.event.ActionListener;
/**
 *
 * @author Safal
 */
public class AdminHouseCardPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminHouseCardPanel
     */
    public AdminHouseCardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlImg = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        lblHouseName = new javax.swing.JLabel();
        lblOwner = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 232), 1, true));
        setPreferredSize(new java.awt.Dimension(1400, 110));
        setLayout(new java.awt.BorderLayout());

        pnlImg.setBackground(new java.awt.Color(238, 242, 255));
        pnlImg.setPreferredSize(new java.awt.Dimension(120, 90));

        lblImage.setText("jLabel1");
        lblImage.setPreferredSize(new java.awt.Dimension(120, 90));

        javax.swing.GroupLayout pnlImgLayout = new javax.swing.GroupLayout(pnlImg);
        pnlImg.setLayout(pnlImgLayout);
        pnlImgLayout.setHorizontalGroup(
            pnlImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImgLayout.createSequentialGroup()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlImgLayout.setVerticalGroup(
            pnlImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        add(pnlImg, java.awt.BorderLayout.WEST);

        pnlInfo.setLayout(new javax.swing.BoxLayout(pnlInfo, javax.swing.BoxLayout.Y_AXIS));

        lblHouseName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHouseName.setText("jLabel1");
        pnlInfo.add(lblHouseName);

        lblOwner.setForeground(new java.awt.Color(102, 102, 102));
        lblOwner.setText("jLabel2");
        pnlInfo.add(lblOwner);

        lblLocation.setForeground(new java.awt.Color(102, 102, 102));
        lblLocation.setText("jLabel3");
        pnlInfo.add(lblLocation);

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(0, 102, 255));
        lblPrice.setText("jLabel4");
        pnlInfo.add(lblPrice);

        add(pnlInfo, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 90));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        lblStatus.setForeground(new java.awt.Color(210, 130, 0));
        lblStatus.setText("jLabel1");
        jPanel1.add(lblStatus);

        btnApprove.setBackground(new java.awt.Color(34, 160, 70));
        btnApprove.setForeground(new java.awt.Color(255, 255, 255));
        btnApprove.setText("jButton1");
        btnApprove.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(btnApprove);

        btnReject.setForeground(new java.awt.Color(220, 50, 50));
        btnReject.setText("jButton1");
        btnReject.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(btnReject);

        add(jPanel1, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents
public void setData(model.House h) {
        lblHouseName.setText(h.getName());
        lblOwner.setText("Owner ID: " + h.getOwnerId());
        lblLocation.setText("📍 " + h.getLocation());
        lblPrice.setText(h.getPrice() != null ? h.getPrice() : "N/A");

        String s = h.getStatus() != null ? h.getStatus().toLowerCase() : "pending";
        switch (s) {
            case "approved":
                lblStatus.setText("✅ Approved");
                lblStatus.setForeground(new java.awt.Color(30, 150, 60));
                btnApprove.setEnabled(false);
                btnReject.setEnabled(false);
                break;
            case "rejected":
                lblStatus.setText("❌ Rejected");
                lblStatus.setForeground(new java.awt.Color(210, 50, 50));
                btnApprove.setEnabled(false);
                btnReject.setEnabled(false);
                break;
            default:
                lblStatus.setText("⏳ Pending");
                lblStatus.setForeground(new java.awt.Color(210, 130, 0));
                btnApprove.setEnabled(true);
                btnReject.setEnabled(true);
        }
    }
    public void setApproveListener(ActionListener l) {
        btnApprove.addActionListener(l);
    }

    public void setRejectListener(ActionListener l) {
        btnReject.addActionListener(l);
    }

// Methods (paste above variables declaration):

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnReject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHouseName;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblOwner;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlImg;
    private javax.swing.JPanel pnlInfo;
    // End of variables declaration//GEN-END:variables


}
