/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.HouseController;
import dao.HouseDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.House;

/**
 *
 * @author Safal
 */
public class AdminHouseApproval extends javax.swing.JFrame {

    private final HouseDAO houseDAO = new HouseDAO();
    private javax.swing.JLabel lblCount;

    public AdminHouseApproval() {
        initComponents();
        loadHouses(null); // Load all by default
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel36 = new javax.swing.JLabel();
        GharSathi_Text = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        SearchHouse_Button = new javax.swing.JButton();
        Bookings_Button = new javax.swing.JButton();
        Post_a_Notice = new javax.swing.JButton();
        Profile_Button = new javax.swing.JButton();
        Dashboard_Button = new javax.swing.JButton();
        Menuelogo_Button = new javax.swing.JButton();
        Username_Text = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnAll = new javax.swing.JButton();
        btnPending = new javax.swing.JButton();
        btnApproved = new javax.swing.JButton();
        btnRejected = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlHouses = new javax.swing.JPanel();
        lblEmpty = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(247, 248, 252));
        setSize(new java.awt.Dimension(1536, 864));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel36.setText("House Rental ");
        jLabel36.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 250, 40));

        GharSathi_Text.setBackground(new java.awt.Color(243, 243, 243));
        GharSathi_Text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GharSathi_Text.setText("System");
        GharSathi_Text.setBorder(null);
        GharSathi_Text.addActionListener(this::GharSathi_TextActionPerformed);
        getContentPane().add(GharSathi_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 220, 50));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GharSathi_Logo.png"))); // NOI18N
        jLabel31.setText("jLabel31");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 120, 100));

        SearchHouse_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SearchHouse_Button.setText("Search Houses");
        SearchHouse_Button.addActionListener(this::SearchHouse_ButtonActionPerformed);
        getContentPane().add(SearchHouse_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 260, 50));

        Bookings_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Bookings_Button.setText("Bookings");
        Bookings_Button.addActionListener(this::Bookings_ButtonActionPerformed);
        getContentPane().add(Bookings_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 260, 50));

        Post_a_Notice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Post_a_Notice.setText("Post a Notice");
        Post_a_Notice.addActionListener(this::Post_a_NoticeActionPerformed);
        getContentPane().add(Post_a_Notice, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 130, 260, 50));

        Profile_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Profile_Button.setText("Profile");
        Profile_Button.addActionListener(this::Profile_ButtonActionPerformed);
        getContentPane().add(Profile_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 130, 260, 50));

        Dashboard_Button.setBackground(new java.awt.Color(15, 75, 155));
        Dashboard_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Dashboard_Button.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard_Button.setText("Dashboard");
        Dashboard_Button.addActionListener(this::Dashboard_ButtonActionPerformed);
        getContentPane().add(Dashboard_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 250, 50));

        Menuelogo_Button.setBackground(new java.awt.Color(243, 243, 243));
        Menuelogo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu.png"))); // NOI18N
        Menuelogo_Button.setBorder(null);
        Menuelogo_Button.addActionListener(this::Menuelogo_ButtonActionPerformed);
        getContentPane().add(Menuelogo_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 0, 50, 30));

        Username_Text.setBackground(new java.awt.Color(243, 243, 243));
        Username_Text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Username_Text.setText("Hello, User");
        Username_Text.setBorder(null);
        Username_Text.addActionListener(this::Username_TextActionPerformed);
        getContentPane().add(Username_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 50, -1, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account_circle.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 30, 40, 60));

        btnAll.setBackground(new java.awt.Color(0, 102, 255));
        btnAll.setForeground(new java.awt.Color(255, 255, 255));
        btnAll.setText("All");
        btnAll.addActionListener(this::btnAllActionPerformed);
        getContentPane().add(btnAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, 36));

        btnPending.setBackground(new java.awt.Color(243, 243, 247));
        btnPending.setForeground(new java.awt.Color(80, 80, 120));
        btnPending.setText("Pending");
        btnPending.addActionListener(this::btnPendingActionPerformed);
        getContentPane().add(btnPending, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 110, 36));

        btnApproved.setBackground(new java.awt.Color(243, 243, 247));
        btnApproved.setForeground(new java.awt.Color(80, 80, 120));
        btnApproved.setText("Approved");
        btnApproved.addActionListener(this::btnApprovedActionPerformed);
        getContentPane().add(btnApproved, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 120, 36));

        btnRejected.setBackground(new java.awt.Color(243, 243, 247));
        btnRejected.setForeground(new java.awt.Color(80, 80, 120));
        btnRejected.setText("Rejected");
        btnRejected.addActionListener(this::btnRejectedActionPerformed);
        getContentPane().add(btnRejected, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 120, 36));

        pnlHouses.setBackground(new java.awt.Color(247, 248, 252));
        pnlHouses.setLayout(new javax.swing.BoxLayout(pnlHouses, javax.swing.BoxLayout.Y_AXIS));

        lblEmpty.setText("No houses found.");
        pnlHouses.add(lblEmpty);

        jScrollPane1.setViewportView(pnlHouses);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 275, 1450, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void loadHouses(String status) {
    pnlHouses.removeAll();

    List<House> list;
    if (status == null || "All".equalsIgnoreCase(status)) {
        list = houseDAO.getAllHouses();
    } else if ("pending".equalsIgnoreCase(status)) {
        list = houseDAO.getPendingHouses();
    } else if ("approved".equalsIgnoreCase(status)) {
        list = houseDAO.getApprovedHouses();
    } else {
        list = houseDAO.getAllHouses();
    }

    // Update count label safely
    if (lblCount != null) {
        lblCount.setText(list.size() + " houses");
    }

    if (list.isEmpty()) {
        lblEmpty.setVisible(true);
        pnlHouses.add(lblEmpty);
    } else {
        lblEmpty.setVisible(false);
        for (House h : list) {
            AdminHouseCardPanel card = new AdminHouseCardPanel();
            card.setData(h);

            card.setApproveListener(e -> doApprove(h, card));
            card.setRejectListener(e -> doReject(h, card));

            card.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 120));
            pnlHouses.add(card);
            pnlHouses.add(javax.swing.Box.createVerticalStrut(10));
        }
    }

    pnlHouses.revalidate();
    pnlHouses.repaint();
}
    private void doApprove(House h, AdminHouseCardPanel card) {
        int confirm = JOptionPane.showConfirmDialog(this, "Approve house: " + h.getName() + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (houseDAO.updateStatus(h.getId(), "approved")) {
                h.setStatus("approved");
                card.setData(h);
                JOptionPane.showMessageDialog(this, "House approved successfully!");
            }
        }
    }

    private void doReject(House h, AdminHouseCardPanel card) {
        int confirm = JOptionPane.showConfirmDialog(this, "Reject house: " + h.getName() + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (houseDAO.updateStatus(h.getId(), "rejected")) {
                h.setStatus("rejected");
                card.setData(h);
                JOptionPane.showMessageDialog(this, "House rejected.");
            }
        }
    }

    private void resetTabs() {
        Color bg = new java.awt.Color(243, 243, 247);
        Color fg = new java.awt.Color(80, 80, 120);
        for (JButton b : new JButton[]{btnAll, btnPending, btnApproved, btnRejected}) {
            b.setBackground(bg);
            b.setForeground(fg);
        }
    }

    private void activateTab(JButton b) {
        b.setBackground(new java.awt.Color(0, 102, 255));
        b.setForeground(Color.WHITE);
    }
    private void GharSathi_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GharSathi_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GharSathi_TextActionPerformed

    private void SearchHouse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchHouse_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchHouse_ButtonActionPerformed

    private void Bookings_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bookings_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bookings_ButtonActionPerformed

    private void Post_a_NoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Post_a_NoticeActionPerformed
                                           
    new AdminNotice().setVisible(true);

     // TODO add your handling code here:
    }//GEN-LAST:event_Post_a_NoticeActionPerformed

    private void Profile_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_ButtonActionPerformed

    private void Dashboard_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dashboard_ButtonActionPerformed

    private void Menuelogo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menuelogo_ButtonActionPerformed
     HouseController houseController = new HouseController();

    DashBoard dashboard = new DashBoard(houseController);
    dashboard.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_Menuelogo_ButtonActionPerformed

    private void Username_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_TextActionPerformed

    private void btnPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendingActionPerformed
      resetTabs();
        activateTab(btnPending);
        loadHouses("pending");  // TODO add your handling code here:
    }//GEN-LAST:event_btnPendingActionPerformed

    private void btnApprovedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovedActionPerformed
     resetTabs();
        activateTab(btnApproved);
        loadHouses("approved");   // TODO add your handling code here:
    }//GEN-LAST:event_btnApprovedActionPerformed

    private void btnRejectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectedActionPerformed
      resetTabs();
        activateTab(btnRejected);
        loadHouses("rejected");  // TODO add your handling code here:
    }//GEN-LAST:event_btnRejectedActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
       resetTabs();
        activateTab(btnAll);
        loadHouses("All"); // TODO add your handling code here:
    }//GEN-LAST:event_btnAllActionPerformed

    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new AdminHouseApproval().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bookings_Button;
    private javax.swing.JButton Dashboard_Button;
    private javax.swing.JTextField GharSathi_Text;
    private javax.swing.JButton Menuelogo_Button;
    private javax.swing.JButton Post_a_Notice;
    private javax.swing.JButton Profile_Button;
    private javax.swing.JButton SearchHouse_Button;
    private javax.swing.JTextField Username_Text;
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnApproved;
    private javax.swing.JButton btnPending;
    private javax.swing.JButton btnRejected;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmpty;
    private javax.swing.JPanel pnlHouses;
    // End of variables declaration//GEN-END:variables
}