/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Safal
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form Login
     */
public AdminDashboard() {
    initComponents();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel36 = new javax.swing.JLabel();
        GharSathi_Text = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        SearchHouse_Button = new javax.swing.JButton();
        Bookings_Button = new javax.swing.JButton();
        Post_a_Notice = new javax.swing.JButton();
        Profile_Button = new javax.swing.JButton();
        Dashboard_Button = new javax.swing.JButton();
        House1Price_Text = new javax.swing.JTextField();
        House1Name_Text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RecommendedHouse2_BUtton1 = new javax.swing.JButton();
        ViewAll_Button = new javax.swing.JButton();
        RecommendedHouse_Text = new javax.swing.JTextField();
        RecentActitivity_Text = new javax.swing.JTextField();
        Recent3_Text = new javax.swing.JTextField();
        Recent2_Text = new javax.swing.JTextField();
        Recent1_Text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        House1Price_Text1 = new javax.swing.JTextField();
        House1Name_Text1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RecommendedHouse2_BUtton3 = new javax.swing.JButton();
        House1Price_Text2 = new javax.swing.JTextField();
        House1Name_Text2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RecommendedHouse2_BUtton4 = new javax.swing.JButton();
        House1Price_Text3 = new javax.swing.JTextField();
        House1Name_Text3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        RecommendedHouse2_BUtton5 = new javax.swing.JButton();
        House1Price_Text4 = new javax.swing.JTextField();
        House1Name_Text4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        RecommendedHouse2_BUtton6 = new javax.swing.JButton();
        House1Price_Text5 = new javax.swing.JTextField();
        House1Name_Text5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        RecommendedHouse2_BUtton7 = new javax.swing.JButton();
        House1Price_Text6 = new javax.swing.JTextField();
        House1Name_Text6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        RecommendedHouse2_BUtton8 = new javax.swing.JButton();
        House1Price_Text7 = new javax.swing.JTextField();
        House1Name_Text7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        RecommendedHouse2_BUtton9 = new javax.swing.JButton();
        House1Price_Text8 = new javax.swing.JTextField();
        House1Name_Text8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        RecommendedHouse2_BUtton10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Menuelogo_Button = new javax.swing.JButton();
        Username_Text = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Iconlogo_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1536, 864));
        getContentPane().setLayout(null);

        jLabel36.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel36.setText("House Rental ");
        jLabel36.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel36);
        jLabel36.setBounds(110, 10, 250, 40);

        GharSathi_Text.setBackground(new java.awt.Color(243, 243, 243));
        GharSathi_Text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GharSathi_Text.setText("System");
        GharSathi_Text.setBorder(null);
        GharSathi_Text.addActionListener(this::GharSathi_TextActionPerformed);
        getContentPane().add(GharSathi_Text);
        GharSathi_Text.setBounds(110, 20, 220, 50);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Rectangle 4_1.png"))); // NOI18N
        jLabel31.setText("jLabel31");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(-20, -10, 120, 120);

        SearchHouse_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SearchHouse_Button.setText("Search Houses");
        SearchHouse_Button.addActionListener(this::SearchHouse_ButtonActionPerformed);
        getContentPane().add(SearchHouse_Button);
        SearchHouse_Button.setBounds(420, 130, 260, 50);

        Bookings_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Bookings_Button.setText("Bookings");
        Bookings_Button.addActionListener(this::Bookings_ButtonActionPerformed);
        getContentPane().add(Bookings_Button);
        Bookings_Button.setBounds(680, 130, 260, 50);

        Post_a_Notice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Post_a_Notice.setText("Post a Notice");
        Post_a_Notice.addActionListener(this::Post_a_NoticeActionPerformed);
        getContentPane().add(Post_a_Notice);
        Post_a_Notice.setBounds(940, 130, 260, 50);

        Profile_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Profile_Button.setText("Profile");
        Profile_Button.addActionListener(this::Profile_ButtonActionPerformed);
        getContentPane().add(Profile_Button);
        Profile_Button.setBounds(1200, 130, 260, 50);

        Dashboard_Button.setBackground(new java.awt.Color(15, 75, 155));
        Dashboard_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Dashboard_Button.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard_Button.setText("Dashboard");
        Dashboard_Button.addActionListener(this::Dashboard_ButtonActionPerformed);
        getContentPane().add(Dashboard_Button);
        Dashboard_Button.setBounds(90, 130, 250, 50);

        House1Price_Text.setBackground(new java.awt.Color(243, 243, 243));
        House1Price_Text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        House1Price_Text.setForeground(new java.awt.Color(53, 100, 166));
        House1Price_Text.setText("Rs,45K/month");
        House1Price_Text.setBorder(null);
        House1Price_Text.addActionListener(this::House1Price_TextActionPerformed);
        getContentPane().add(House1Price_Text);
        House1Price_Text.setBounds(70, 750, 130, 20);

        House1Name_Text.setBackground(new java.awt.Color(243, 243, 243));
        House1Name_Text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        House1Name_Text.setText("Modern Apartment");
        House1Name_Text.setBorder(null);
        House1Name_Text.addActionListener(this::House1Name_TextActionPerformed);
        getContentPane().add(House1Name_Text);
        House1Name_Text.setBounds(70, 710, 230, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/download (2).jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 590, 200, 130);

        RecommendedHouse2_BUtton1.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse2_BUtton1.addActionListener(this::RecommendedHouse2_BUtton1ActionPerformed);
        getContentPane().add(RecommendedHouse2_BUtton1);
        RecommendedHouse2_BUtton1.setBounds(50, 580, 260, 200);

        ViewAll_Button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewAll_Button.setForeground(new java.awt.Color(53, 100, 166));
        ViewAll_Button.setText("View All");
        getContentPane().add(ViewAll_Button);
        ViewAll_Button.setBounds(820, 520, 90, 30);

        RecommendedHouse_Text.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse_Text.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RecommendedHouse_Text.setForeground(new java.awt.Color(53, 100, 166));
        RecommendedHouse_Text.setText("Recommended Houses");
        RecommendedHouse_Text.setBorder(null);
        RecommendedHouse_Text.addActionListener(this::RecommendedHouse_TextActionPerformed);
        getContentPane().add(RecommendedHouse_Text);
        RecommendedHouse_Text.setBounds(50, 520, 300, 32);

        RecentActitivity_Text.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        RecentActitivity_Text.setForeground(new java.awt.Color(53, 100, 166));
        RecentActitivity_Text.setText("Recent Activity");
        RecentActitivity_Text.addActionListener(this::RecentActitivity_TextActionPerformed);
        getContentPane().add(RecentActitivity_Text);
        RecentActitivity_Text.setBounds(1030, 520, 410, 90);

        Recent3_Text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Recent3_Text.setText("CozyHome                         2026/1/10");
        Recent3_Text.setToolTipText("");
        Recent3_Text.addActionListener(this::Recent3_TextActionPerformed);
        getContentPane().add(Recent3_Text);
        Recent3_Text.setBounds(1030, 730, 410, 60);

        Recent2_Text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Recent2_Text.setText("3BHK Flat                           2026/2/4");
        Recent2_Text.setToolTipText("");
        Recent2_Text.addActionListener(this::Recent2_TextActionPerformed);
        getContentPane().add(Recent2_Text);
        Recent2_Text.setBounds(1030, 670, 410, 60);

        Recent1_Text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Recent1_Text.setText("Rented Villa                       2026/1/8");
        Recent1_Text.addActionListener(this::Recent1_TextActionPerformed);
        getContentPane().add(Recent1_Text);
        Recent1_Text.setBounds(1030, 610, 410, 60);

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1030, 520, 410, 270);

        House1Price_Text1.setBackground(new java.awt.Color(243, 243, 243));
        House1Price_Text1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        House1Price_Text1.setForeground(new java.awt.Color(53, 100, 166));
        House1Price_Text1.setText("Rs,45K/month");
        House1Price_Text1.setBorder(null);
        House1Price_Text1.addActionListener(this::House1Price_Text1ActionPerformed);
        getContentPane().add(House1Price_Text1);
        House1Price_Text1.setBounds(70, 750, 130, 20);

        House1Name_Text1.setBackground(new java.awt.Color(243, 243, 243));
        House1Name_Text1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        House1Name_Text1.setText("Modern Apartment");
        House1Name_Text1.setBorder(null);
        House1Name_Text1.addActionListener(this::House1Name_Text1ActionPerformed);
        getContentPane().add(House1Name_Text1);
        House1Name_Text1.setBounds(70, 710, 230, 40);

        jLabel5.setText("jLabel4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 590, 240, 120);

        RecommendedHouse2_BUtton3.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse2_BUtton3.addActionListener(this::RecommendedHouse2_BUtton3ActionPerformed);
        getContentPane().add(RecommendedHouse2_BUtton3);
        RecommendedHouse2_BUtton3.setBounds(50, 580, 260, 200);

        House1Price_Text2.setBackground(new java.awt.Color(243, 243, 243));
        House1Price_Text2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        House1Price_Text2.setForeground(new java.awt.Color(53, 100, 166));
        House1Price_Text2.setText("Rs,45K/month");
        House1Price_Text2.setBorder(null);
        House1Price_Text2.addActionListener(this::House1Price_Text2ActionPerformed);
        getContentPane().add(House1Price_Text2);
        House1Price_Text2.setBounds(70, 750, 130, 20);

        House1Name_Text2.setBackground(new java.awt.Color(243, 243, 243));
        House1Name_Text2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        House1Name_Text2.setText("Modern Apartment");
        House1Name_Text2.setBorder(null);
        House1Name_Text2.addActionListener(this::House1Name_Text2ActionPerformed);
        getContentPane().add(House1Name_Text2);
        House1Name_Text2.setBounds(70, 710, 230, 40);

        jLabel6.setText("jLabel4");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 590, 240, 120);

        RecommendedHouse2_BUtton4.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse2_BUtton4.addActionListener(this::RecommendedHouse2_BUtton4ActionPerformed);
        getContentPane().add(RecommendedHouse2_BUtton4);
        RecommendedHouse2_BUtton4.setBounds(50, 580, 260, 200);

        House1Price_Text3.setBackground(new java.awt.Color(243, 243, 243));
        House1Price_Text3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        House1Price_Text3.setForeground(new java.awt.Color(53, 100, 166));
        House1Price_Text3.setText("Rs,25K/month");
        House1Price_Text3.setBorder(null);
        House1Price_Text3.addActionListener(this::House1Price_Text3ActionPerformed);
        getContentPane().add(House1Price_Text3);
        House1Price_Text3.setBounds(390, 750, 130, 20);

        House1Name_Text3.setBackground(new java.awt.Color(243, 243, 243));
        House1Name_Text3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        House1Name_Text3.setText("Luxury Villa");
        House1Name_Text3.setBorder(null);
        House1Name_Text3.addActionListener(this::House1Name_Text3ActionPerformed);
        getContentPane().add(House1Name_Text3);
        House1Name_Text3.setBounds(390, 710, 220, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/download (3).jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(390, 590, 240, 120);

        RecommendedHouse2_BUtton5.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse2_BUtton5.addActionListener(this::RecommendedHouse2_BUtton5ActionPerformed);
        getContentPane().add(RecommendedHouse2_BUtton5);
        RecommendedHouse2_BUtton5.setBounds(360, 580, 260, 200);

        House1Price_Text4.setBackground(new java.awt.Color(243, 243, 243));
        House1Price_Text4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        House1Price_Text4.setForeground(new java.awt.Color(53, 100, 166));
        House1Price_Text4.setText("Rs,45K/month");
        House1Price_Text4.setBorder(null);
        House1Price_Text4.addActionListener(this::House1Price_Text4ActionPerformed);
        getContentPane().add(House1Price_Text4);
        House1Price_Text4.setBounds(380, 750, 130, 20);

        House1Name_Text4.setBackground(new java.awt.Color(243, 243, 243));
        House1Name_Text4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        House1Name_Text4.setText("Modern Apartment");
        House1Name_Text4.setBorder(null);
        House1Name_Text4.addActionListener(this::House1Name_Text4ActionPerformed);
        getContentPane().add(House1Name_Text4);
        House1Name_Text4.setBounds(380, 710, 230, 40);

        jLabel9.setText("jLabel4");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(370, 590, 240, 120);

        RecommendedHouse2_BUtton6.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse2_BUtton6.addActionListener(this::RecommendedHouse2_BUtton6ActionPerformed);
        getContentPane().add(RecommendedHouse2_BUtton6);
        RecommendedHouse2_BUtton6.setBounds(360, 580, 260, 200);

        House1Price_Text5.setBackground(new java.awt.Color(243, 243, 243));
        House1Price_Text5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        House1Price_Text5.setForeground(new java.awt.Color(53, 100, 166));
        House1Price_Text5.setText("Rs,45K/month");
        House1Price_Text5.setBorder(null);
        House1Price_Text5.addActionListener(this::House1Price_Text5ActionPerformed);
        getContentPane().add(House1Price_Text5);
        House1Price_Text5.setBounds(380, 750, 130, 20);

        House1Name_Text5.setBackground(new java.awt.Color(243, 243, 243));
        House1Name_Text5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        House1Name_Text5.setText("Modern Apartment");
        House1Name_Text5.setBorder(null);
        House1Name_Text5.addActionListener(this::House1Name_Text5ActionPerformed);
        getContentPane().add(House1Name_Text5);
        House1Name_Text5.setBounds(380, 710, 230, 40);

        jLabel10.setText("jLabel4");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(370, 590, 240, 120);

        RecommendedHouse2_BUtton7.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse2_BUtton7.addActionListener(this::RecommendedHouse2_BUtton7ActionPerformed);
        getContentPane().add(RecommendedHouse2_BUtton7);
        RecommendedHouse2_BUtton7.setBounds(360, 580, 260, 200);

        House1Price_Text6.setBackground(new java.awt.Color(243, 243, 243));
        House1Price_Text6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        House1Price_Text6.setForeground(new java.awt.Color(53, 100, 166));
        House1Price_Text6.setText("Rs,32K/month");
        House1Price_Text6.setBorder(null);
        House1Price_Text6.addActionListener(this::House1Price_Text6ActionPerformed);
        getContentPane().add(House1Price_Text6);
        House1Price_Text6.setBounds(680, 750, 130, 20);

        House1Name_Text6.setBackground(new java.awt.Color(243, 243, 243));
        House1Name_Text6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        House1Name_Text6.setText("Cozy Home");
        House1Name_Text6.setBorder(null);
        House1Name_Text6.addActionListener(this::House1Name_Text6ActionPerformed);
        getContentPane().add(House1Name_Text6);
        House1Name_Text6.setBounds(680, 710, 230, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/download (4).jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(690, 590, 230, 120);

        RecommendedHouse2_BUtton8.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse2_BUtton8.addActionListener(this::RecommendedHouse2_BUtton8ActionPerformed);
        getContentPane().add(RecommendedHouse2_BUtton8);
        RecommendedHouse2_BUtton8.setBounds(660, 580, 260, 200);

        House1Price_Text7.setBackground(new java.awt.Color(243, 243, 243));
        House1Price_Text7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        House1Price_Text7.setForeground(new java.awt.Color(53, 100, 166));
        House1Price_Text7.setText("Rs,45K/month");
        House1Price_Text7.setBorder(null);
        House1Price_Text7.addActionListener(this::House1Price_Text7ActionPerformed);
        getContentPane().add(House1Price_Text7);
        House1Price_Text7.setBounds(680, 750, 130, 20);

        House1Name_Text7.setBackground(new java.awt.Color(243, 243, 243));
        House1Name_Text7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        House1Name_Text7.setText("Modern Apartment");
        House1Name_Text7.setBorder(null);
        House1Name_Text7.addActionListener(this::House1Name_Text7ActionPerformed);
        getContentPane().add(House1Name_Text7);
        House1Name_Text7.setBounds(680, 710, 230, 40);

        jLabel13.setText("jLabel4");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(670, 590, 240, 120);

        RecommendedHouse2_BUtton9.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse2_BUtton9.addActionListener(this::RecommendedHouse2_BUtton9ActionPerformed);
        getContentPane().add(RecommendedHouse2_BUtton9);
        RecommendedHouse2_BUtton9.setBounds(660, 580, 260, 200);

        House1Price_Text8.setBackground(new java.awt.Color(243, 243, 243));
        House1Price_Text8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        House1Price_Text8.setForeground(new java.awt.Color(53, 100, 166));
        House1Price_Text8.setText("Rs,45K/month");
        House1Price_Text8.setBorder(null);
        House1Price_Text8.addActionListener(this::House1Price_Text8ActionPerformed);
        getContentPane().add(House1Price_Text8);
        House1Price_Text8.setBounds(680, 750, 130, 20);

        House1Name_Text8.setBackground(new java.awt.Color(243, 243, 243));
        House1Name_Text8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        House1Name_Text8.setText("Modern Apartment");
        House1Name_Text8.setBorder(null);
        House1Name_Text8.addActionListener(this::House1Name_Text8ActionPerformed);
        getContentPane().add(House1Name_Text8);
        House1Name_Text8.setBounds(680, 710, 230, 40);

        jLabel14.setText("jLabel4");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(670, 590, 240, 120);

        RecommendedHouse2_BUtton10.setBackground(new java.awt.Color(243, 243, 243));
        RecommendedHouse2_BUtton10.addActionListener(this::RecommendedHouse2_BUtton10ActionPerformed);
        getContentPane().add(RecommendedHouse2_BUtton10);
        RecommendedHouse2_BUtton10.setBounds(660, 580, 260, 200);

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 510, 930, 280);

        Menuelogo_Button.setBackground(new java.awt.Color(243, 243, 243));
        Menuelogo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Vector (1).png"))); // NOI18N
        Menuelogo_Button.setBorder(null);
        Menuelogo_Button.addActionListener(this::Menuelogo_ButtonActionPerformed);
        getContentPane().add(Menuelogo_Button);
        Menuelogo_Button.setBounds(1490, 0, 50, 30);

        Username_Text.setBackground(new java.awt.Color(243, 243, 243));
        Username_Text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Username_Text.setText("Hello, User");
        Username_Text.setBorder(null);
        Username_Text.addActionListener(this::Username_TextActionPerformed);
        getContentPane().add(Username_Text);
        Username_Text.setBounds(1370, 50, 116, 20);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/account_circle.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1320, 30, 40, 60);

        Iconlogo_Button.setBackground(new java.awt.Color(242, 242, 242));
        Iconlogo_Button.setForeground(new java.awt.Color(242, 242, 242));
        Iconlogo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/download__6_-removebg-preview_1.png"))); // NOI18N
        Iconlogo_Button.setBorder(null);
        Iconlogo_Button.addActionListener(this::Iconlogo_ButtonActionPerformed);
        getContentPane().add(Iconlogo_Button);
        Iconlogo_Button.setBounds(1220, 20, 80, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GharSathi_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GharSathi_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GharSathi_TextActionPerformed

    private void SearchHouse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchHouse_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchHouse_ButtonActionPerformed

    private void Bookings_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bookings_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bookings_ButtonActionPerformed

    private void Post_a_NoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Post_a_NoticeActionPerformed
                                           
    new AdminNotice().setVisible(true);

     // TODO add your handling code here:
    }//GEN-LAST:event_Post_a_NoticeActionPerformed

    private void Profile_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_ButtonActionPerformed

    private void Dashboard_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dashboard_ButtonActionPerformed

    private void RecommendedHouse2_BUtton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse2_BUtton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse2_BUtton1ActionPerformed

    private void RecommendedHouse_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse_TextActionPerformed

    private void Recent2_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recent2_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Recent2_TextActionPerformed

    private void Recent1_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recent1_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Recent1_TextActionPerformed

    private void RecentActitivity_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecentActitivity_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecentActitivity_TextActionPerformed

    private void House1Price_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Price_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Price_TextActionPerformed

    private void House1Name_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Name_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Name_TextActionPerformed

    private void House1Price_Text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Price_Text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Price_Text1ActionPerformed

    private void House1Name_Text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Name_Text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Name_Text1ActionPerformed

    private void RecommendedHouse2_BUtton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse2_BUtton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse2_BUtton3ActionPerformed

    private void House1Price_Text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Price_Text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Price_Text2ActionPerformed

    private void House1Name_Text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Name_Text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Name_Text2ActionPerformed

    private void RecommendedHouse2_BUtton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse2_BUtton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse2_BUtton4ActionPerformed

    private void House1Price_Text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Price_Text3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Price_Text3ActionPerformed

    private void House1Name_Text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Name_Text3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Name_Text3ActionPerformed

    private void RecommendedHouse2_BUtton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse2_BUtton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse2_BUtton5ActionPerformed

    private void House1Price_Text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Price_Text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Price_Text4ActionPerformed

    private void House1Name_Text4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Name_Text4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Name_Text4ActionPerformed

    private void RecommendedHouse2_BUtton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse2_BUtton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse2_BUtton6ActionPerformed

    private void House1Price_Text5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Price_Text5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Price_Text5ActionPerformed

    private void House1Name_Text5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Name_Text5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Name_Text5ActionPerformed

    private void RecommendedHouse2_BUtton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse2_BUtton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse2_BUtton7ActionPerformed

    private void House1Price_Text6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Price_Text6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Price_Text6ActionPerformed

    private void House1Name_Text6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Name_Text6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Name_Text6ActionPerformed

    private void RecommendedHouse2_BUtton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse2_BUtton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse2_BUtton8ActionPerformed

    private void House1Price_Text7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Price_Text7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Price_Text7ActionPerformed

    private void House1Name_Text7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Name_Text7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Name_Text7ActionPerformed

    private void RecommendedHouse2_BUtton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse2_BUtton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse2_BUtton9ActionPerformed

    private void House1Price_Text8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Price_Text8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Price_Text8ActionPerformed

    private void House1Name_Text8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_House1Name_Text8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_House1Name_Text8ActionPerformed

    private void RecommendedHouse2_BUtton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommendedHouse2_BUtton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecommendedHouse2_BUtton10ActionPerformed

    private void Recent3_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recent3_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Recent3_TextActionPerformed

    private void Menuelogo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menuelogo_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menuelogo_ButtonActionPerformed

    private void Username_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_TextActionPerformed

    private void Iconlogo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iconlogo_ButtonActionPerformed

    // no notification popup for admin
    // TODO add your handling code here:
    }//GEN-LAST:event_Iconlogo_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
 
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* CRUCIAL: Opens both screens under the exact same process session */
    java.awt.EventQueue.invokeLater(() -> {
        new AdminDashboard().setVisible(true);
        new DashBoard().setVisible(true);
    });

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bookings_Button;
    private javax.swing.JButton Dashboard_Button;
    private javax.swing.JTextField GharSathi_Text;
    private javax.swing.JTextField House1Name_Text;
    private javax.swing.JTextField House1Name_Text1;
    private javax.swing.JTextField House1Name_Text2;
    private javax.swing.JTextField House1Name_Text3;
    private javax.swing.JTextField House1Name_Text4;
    private javax.swing.JTextField House1Name_Text5;
    private javax.swing.JTextField House1Name_Text6;
    private javax.swing.JTextField House1Name_Text7;
    private javax.swing.JTextField House1Name_Text8;
    private javax.swing.JTextField House1Price_Text;
    private javax.swing.JTextField House1Price_Text1;
    private javax.swing.JTextField House1Price_Text2;
    private javax.swing.JTextField House1Price_Text3;
    private javax.swing.JTextField House1Price_Text4;
    private javax.swing.JTextField House1Price_Text5;
    private javax.swing.JTextField House1Price_Text6;
    private javax.swing.JTextField House1Price_Text7;
    private javax.swing.JTextField House1Price_Text8;
    private javax.swing.JButton Iconlogo_Button;
    private javax.swing.JButton Menuelogo_Button;
    private javax.swing.JButton Post_a_Notice;
    private javax.swing.JButton Profile_Button;
    private javax.swing.JTextField Recent1_Text;
    private javax.swing.JTextField Recent2_Text;
    private javax.swing.JTextField Recent3_Text;
    private javax.swing.JTextField RecentActitivity_Text;
    private javax.swing.JButton RecommendedHouse2_BUtton1;
    private javax.swing.JButton RecommendedHouse2_BUtton10;
    private javax.swing.JButton RecommendedHouse2_BUtton3;
    private javax.swing.JButton RecommendedHouse2_BUtton4;
    private javax.swing.JButton RecommendedHouse2_BUtton5;
    private javax.swing.JButton RecommendedHouse2_BUtton6;
    private javax.swing.JButton RecommendedHouse2_BUtton7;
    private javax.swing.JButton RecommendedHouse2_BUtton8;
    private javax.swing.JButton RecommendedHouse2_BUtton9;
    private javax.swing.JTextField RecommendedHouse_Text;
    private javax.swing.JButton SearchHouse_Button;
    private javax.swing.JTextField Username_Text;
    private javax.swing.JButton ViewAll_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}