package view;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import model.Booking;


/**
 *
 * @author Safal
 */
public class BookingCardPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookingCardPanel
     */
   
public BookingCardPanel() {
    initComponents();
      pnlMiddle.setBorder(
        BorderFactory.createEmptyBorder(10,15,10,15)
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMiddle = new javax.swing.JPanel();
        pnlInfo = new javax.swing.JPanel();
        lblHouseName = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        pnlBookingInfo = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        setBorder(
            BorderFactory.createCompoundBorder(

                BorderFactory.createLineBorder(
                    new Color(230,230,230),
                    1,
                    true
                ),

                BorderFactory.createEmptyBorder(
                    10,
                    10,
                    10,
                    10
                )
            )
        );
        pnlImage = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnView = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 230, 230), 1, true));
        setPreferredSize(new java.awt.Dimension(850, 160));
        setLayout(new java.awt.BorderLayout());

        pnlMiddle.setLayout(new java.awt.BorderLayout());

        pnlInfo.setPreferredSize(new java.awt.Dimension(120, 80));
        pnlInfo.setLayout(new javax.swing.BoxLayout(pnlInfo, javax.swing.BoxLayout.Y_AXIS));

        lblHouseName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHouseName.setText("Modern Apartment");
        pnlInfo.add(lblHouseName);

        lblLocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLocation.setText("📍 Pokhara");
        pnlInfo.add(lblLocation);

        lblPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(0, 51, 204));
        lblPrice.setText("Rs.55,000/month");
        pnlInfo.add(lblPrice);

        pnlMiddle.add(pnlInfo, java.awt.BorderLayout.CENTER);

        pnlBookingInfo.setBorder(BorderFactory.createEmptyBorder(0,20,0,20));
        pnlBookingInfo.setPreferredSize(new java.awt.Dimension(160, 80));
        pnlBookingInfo.setLayout(new javax.swing.BoxLayout(pnlBookingInfo, javax.swing.BoxLayout.Y_AXIS));

        lblDate.setText("12 June 2026");
        pnlBookingInfo.add(lblDate);

        lblStatus.setText("Confirmed");
        pnlBookingInfo.add(lblStatus);

        pnlMiddle.add(pnlBookingInfo, java.awt.BorderLayout.EAST);

        add(pnlMiddle, java.awt.BorderLayout.CENTER);

        pnlImage.setPreferredSize(new java.awt.Dimension(120, 100));
        pnlImage.setLayout(new java.awt.BorderLayout());

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setPreferredSize(new java.awt.Dimension(110, 80));
        pnlImage.add(lblImage, java.awt.BorderLayout.CENTER);

        add(pnlImage, java.awt.BorderLayout.WEST);

        pnlButtons.setPreferredSize(new java.awt.Dimension(120, 80));

        btnView.setBackground(new java.awt.Color(0, 102, 255));
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.setPreferredSize(new java.awt.Dimension(80, 30));
        btnView.addActionListener(this::btnViewActionPerformed);
        pnlButtons.add(btnView);

        btnCancel.setForeground(new java.awt.Color(255, 0, 0));
        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(80, 30));
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        pnlButtons.add(btnCancel);

        add(pnlButtons, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
      
    // TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
   
     // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed
public void setData(Booking b) {
        lblHouseName.setText(b.getHouseName() != null ? b.getHouseName() : "Unknown House");
        lblLocation.setText("📍 " + (b.getLocation() != null ? b.getLocation() : ""));
        lblPrice.setText(b.getPrice() != null ? "Rs. " + b.getPrice() + "/month" : "");

        lblDate.setText(b.getBookingDate() != null ? "📅 " + b.getBookingDate() : "");

        String status = (b.getStatus() != null ? b.getStatus() : "pending").toLowerCase();
        lblStatus.setText(status.toUpperCase());
        switch (status) {
            case "confirmed"  -> lblStatus.setForeground(new Color(34, 160, 70));
            case "pending"    -> lblStatus.setForeground(new Color(210, 130, 0));
            case "cancelled"  -> lblStatus.setForeground(new Color(220, 50, 50));
            default           -> lblStatus.setForeground(Color.GRAY);
        }

        // Cancel only visible for pending bookings
        btnCancel.setVisible("pending".equals(status));

        // Load image
        String imgPath = b.getFirstImage();
        if (imgPath != null && !imgPath.isBlank()) {
            loadImage(imgPath);
        }
    }

    private void loadImage(String path) {
        try {
            java.awt.Image img = new javax.swing.ImageIcon(path)
                    .getImage().getScaledInstance(108, 73, java.awt.Image.SCALE_SMOOTH);
            lblImage.setIcon(new javax.swing.ImageIcon(img));
            lblImage.setText("");
        } catch (Exception e) {
            lblImage.setText("No Image");
        }
    }


    public void setCancelListener(java.awt.event.ActionListener listener) {
        if (btnCancel != null) {
            for (var l : btnCancel.getActionListeners()) btnCancel.removeActionListener(l);
            btnCancel.addActionListener(listener);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHouseName;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlBookingInfo;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlMiddle;
    // End of variables declaration//GEN-END:variables
}
