/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.EmailUtility;
import dao.UserDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Safal
 */
public class Forget_Password extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Forget_Password.class.getName());

    /**
     * Creates new form Login
     */
    public Forget_Password() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSignup = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnBackToLogin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1536, 864));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(250, 241, 224));
        jPanel1.setPreferredSize(new java.awt.Dimension(544, 864));
        jPanel1.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("We'll help you ");
        jLabel22.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel22);
        jLabel22.setBounds(60, 580, 680, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Find your perfect home");
        jLabel5.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 250, 360, 40);

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel7.setText("House Rental ");
        jLabel7.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 140, 420, 60);

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel11.setText("           System");
        jLabel11.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(-140, 170, 880, 80);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("your account.    ");
        jLabel23.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel23);
        jLabel23.setBounds(60, 630, 180, 20);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("get back to ");
        jLabel24.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel24);
        jLabel24.setBounds(60, 610, 680, 20);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("is our priority");
        jLabel26.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel26);
        jLabel26.setBounds(190, 730, 680, 30);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(53, 100, 166));
        jLabel30.setText("Welcome Back,");
        jLabel30.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel30);
        jLabel30.setBounds(50, 540, 350, 30);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Rectangle 4_1.png"))); // NOI18N
        jLabel31.setText("jLabel31");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(180, 40, 120, 120);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setText("Your security ");
        jLabel33.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel33);
        jLabel33.setBounds(190, 720, 680, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/_7D47BD78-A051-46AC-9AA6-94ED3E6D9A1F_-removebg-preview 2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 60, 540, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 544, 864);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("OR");
        jLabel3.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(960, 670, 40, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Enter your registerd email ");
        jLabel4.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(650, 150, 880, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        jLabel6.setText("Let's reset your password");
        jLabel6.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(650, 80, 880, 60);

        btnSignup.setBackground(new java.awt.Color(15, 75, 155));
        btnSignup.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Send OTP");
        btnSignup.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSignup.addActionListener(this::btnSignupActionPerformed);
        getContentPane().add(btnSignup);
        btnSignup.setBounds(690, 610, 580, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/download__1_-removebg-preview_1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1240, 540, 60, 50);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(11, 75, 159));
        jLabel10.setText("Forget Password");
        jLabel10.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(650, 30, 880, 40);

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(11, 75, 159));
        jLabel18.setText("House Rental System");
        jLabel18.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(40, 60, 880, 40);

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(11, 75, 159));
        jLabel19.setText("House Rental System");
        jLabel19.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel19);
        jLabel19.setBounds(40, 30, 880, 40);

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(11, 75, 159));
        jLabel20.setText("House Rental System");
        jLabel20.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(40, 50, 880, 40);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel21.setText("Time_Password (OTP)");
        jLabel21.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel21);
        jLabel21.setBounds(650, 210, 880, 30);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("using GharSathi .     ");
        jLabel27.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel27);
        jLabel27.setBounds(60, 740, 680, 20);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("using GharSathi .     ");
        jLabel28.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel28);
        jLabel28.setBounds(60, 740, 680, 20);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("using GharSathi .     ");
        jLabel29.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel29);
        jLabel29.setBounds(60, 740, 680, 20);

        txtEmail.addActionListener(this::txtEmailActionPerformed);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(650, 540, 650, 50);

        btnBackToLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBackToLogin.setForeground(new java.awt.Color(51, 51, 51));
        btnBackToLogin.setText("Back to Login");
        btnBackToLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBackToLogin.addActionListener(this::btnBackToLoginActionPerformed);
        getContentPane().add(btnBackToLogin);
        btnBackToLogin.setBounds(700, 710, 570, 50);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Enter your email");
        jLabel8.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(650, 490, 220, 40);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel32.setText("and we'll send you  a One_");
        jLabel32.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel32);
        jLabel32.setBounds(650, 180, 880, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ChatGPT ImagePM.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(770, 220, 440, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed


    String email = txtEmail.getText().trim();

    if(email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Email");
        return;
    }

    UserDAO dao = new UserDAO();

    if(!dao.emailExists(email)) {
        JOptionPane.showMessageDialog(this, "Email not found");
        return;
    }

    // ← Run email sending in background so UI doesn't freeze
    new Thread(() -> {

        String otp = String.valueOf((int)(Math.random() * 900000) + 100000);
        boolean otpSaved = dao.saveOTP(email, otp);

        if(otpSaved) {
            boolean emailSent = EmailUtility.sendOTP(email, otp);

            javax.swing.SwingUtilities.invokeLater(() -> {
                if(emailSent) {
                    JOptionPane.showMessageDialog(this, "OTP Sent Successfully");
                    VerifyOTP verify = new VerifyOTP(email);
                    verify.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to send email");
                }
            });
        }

    }).start();

    }//GEN-LAST:event_btnSignupActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLoginActionPerformed


    Login login = new Login();
    login.setVisible(true);

    this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_btnBackToLoginActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Forget_Password().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
