/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;



/**
 *
 * @author rojan
 */
public class Myhome extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Myhome.class.getName());

    /**
     * Creates new form profile
     */
    public Myhome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ghar_sathi_icon = new javax.swing.JLabel();
        home_rental = new javax.swing.JLabel();
        system = new javax.swing.JLabel();
        SearchBar_Button = new javax.swing.JButton();
        Iconlogo_Button = new javax.swing.JButton();
        Dashboard_Button = new javax.swing.JButton();
        Users_button = new javax.swing.JButton();
        Bookings_button = new javax.swing.JButton();
        Earnings_button = new javax.swing.JButton();
        My_houses = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        ghar_sathi_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Rectangle 3.png"))); // NOI18N
        getContentPane().add(ghar_sathi_icon);
        ghar_sathi_icon.setBounds(0, 0, 66, 77);

        home_rental.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        home_rental.setText("HOME RENTAL ");
        getContentPane().add(home_rental);
        home_rental.setBounds(72, 14, 100, 16);

        system.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        system.setText("SYSTEM");
        getContentPane().add(system);
        system.setBounds(72, 49, 67, 16);

        SearchBar_Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchBar_Button.setText("Search by Location,house name.......");
        SearchBar_Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SearchBar_Button.addActionListener(this::SearchBar_ButtonActionPerformed);
        getContentPane().add(SearchBar_Button);
        SearchBar_Button.setBounds(229, 36, 717, 40);

        Iconlogo_Button.setBackground(new java.awt.Color(243, 243, 243));
        Iconlogo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Vector (1).png"))); // NOI18N
        Iconlogo_Button.setBorder(null);
        Iconlogo_Button.addActionListener(this::Iconlogo_ButtonActionPerformed);
        getContentPane().add(Iconlogo_Button);
        Iconlogo_Button.setBounds(1200, 30, 50, 30);

        Dashboard_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Dashboard_Button.setText("Dashboard");
        Dashboard_Button.addActionListener(this::Dashboard_ButtonActionPerformed);
        getContentPane().add(Dashboard_Button);
        Dashboard_Button.setBounds(6, 127, 238, 47);

        Users_button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Users_button.setText("Profile");
        Users_button.addActionListener(this::Users_buttonActionPerformed);
        getContentPane().add(Users_button);
        Users_button.setBounds(1020, 130, 240, 47);

        Bookings_button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Bookings_button.setText("Bookings");
        Bookings_button.addActionListener(this::Bookings_buttonActionPerformed);
        getContentPane().add(Bookings_button);
        Bookings_button.setBounds(494, 127, 240, 47);

        Earnings_button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Earnings_button.setText("Earnings");
        Earnings_button.addActionListener(this::Earnings_buttonActionPerformed);
        getContentPane().add(Earnings_button);
        Earnings_button.setBounds(740, 130, 270, 47);

        My_houses.setBackground(new java.awt.Color(15, 75, 155));
        My_houses.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        My_houses.setForeground(new java.awt.Color(255, 255, 255));
        My_houses.setText("My Houses");
        My_houses.addActionListener(this::My_housesActionPerformed);
        getContentPane().add(My_houses);
        My_houses.setBounds(250, 127, 240, 47);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modernhouse.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(6, 32, 100, 75);

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("📞9751850123");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 80, 130, 16);

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Cooy Home");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(130, 60, 130, 16);

        jLabel14.setText("Sam Wilson");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(130, 30, 63, 27);

        jButton3.setBackground(new java.awt.Color(51, 153, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Accept");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3);
        jButton3.setBounds(917, 87, 125, 46);

        jButton6.setForeground(new java.awt.Color(255, 0, 0));
        jButton6.setText("Reject");
        jPanel1.add(jButton6);
        jButton6.setBounds(1060, 87, 133, 46);

        jLabel17.setForeground(new java.awt.Color(255, 102, 102));
        jLabel17.setText("Pending");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(724, 58, 76, 16);

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("12 May 2025");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(724, 32, 130, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 540, 1250, 160);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modernhouse.jpg"))); // NOI18N

        jLabel9.setText("Michael Smith");

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Luxury Villa");

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("📞98021366642");

        jButton4.setBackground(new java.awt.Color(51, 153, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Accept");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Reject");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel16.setForeground(new java.awt.Color(255, 102, 102));
        jLabel16.setText("Pending");

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("12 May 2025");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(396, 396, 396))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 370, 1250, 160);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modernhouse.jpg"))); // NOI18N

        jLabel1.setText("John Doe");

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Modern Apartment");

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("📞98012567");

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("12 May 2025");

        jButton2.setBackground(new java.awt.Color(51, 153, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Accept");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("Pending");

        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("Reject");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 491, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(375, 375, 375))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(10, 200, 1250, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBar_ButtonActionPerformed
        // TODO add your handling cod
    }//GEN-LAST:event_SearchBar_ButtonActionPerformed

    private void Iconlogo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iconlogo_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Iconlogo_ButtonActionPerformed

    private void Dashboard_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dashboard_ButtonActionPerformed

    private void Users_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Users_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Users_buttonActionPerformed

    private void Bookings_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bookings_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bookings_buttonActionPerformed

    private void Earnings_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Earnings_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Earnings_buttonActionPerformed

    private void My_housesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_My_housesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_My_housesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Myhome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bookings_button;
    private javax.swing.JButton Dashboard_Button;
    private javax.swing.JButton Earnings_button;
    private javax.swing.JButton Iconlogo_Button;
    private javax.swing.JButton My_houses;
    private javax.swing.JButton SearchBar_Button;
    private javax.swing.JButton Users_button;
    private javax.swing.JLabel ghar_sathi_icon;
    private javax.swing.JLabel home_rental;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel system;
    // End of variables declaration//GEN-END:variables
}
