package view;

import model.Booking;
import database.db;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

public class OwnerBookingCardPanel extends javax.swing.JPanel {
       // shown when status is NOT pending
 
    // ── Constructor ────────────────────────────────────────────────────────────
    public OwnerBookingCardPanel() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlImage = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        pnlBookingInfo = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        lblCustomerName = new javax.swing.JLabel();
        lblHouseName = new javax.swing.JLabel();
        lblCustomerId = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(860, 150));
        setLayout(new java.awt.BorderLayout());

        pnlImage.setOpaque(false);
        pnlImage.setPreferredSize(new java.awt.Dimension(110, 110));
        pnlImage.setLayout(new java.awt.BorderLayout());

        lblImage.setBackground(new java.awt.Color(240, 240, 240));
        lblImage.setForeground(new java.awt.Color(102, 102, 102));
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("No Image");
        lblImage.setOpaque(true);
        lblImage.setPreferredSize(new java.awt.Dimension(108, 80));
        pnlImage.add(lblImage, java.awt.BorderLayout.CENTER);

        add(pnlImage, java.awt.BorderLayout.WEST);

        pnlCenter.setOpaque(false);
        pnlCenter.setLayout(new java.awt.BorderLayout());

        pnlBookingInfo.setOpaque(false);
        pnlBookingInfo.setPreferredSize(new java.awt.Dimension(160, 80));
        pnlBookingInfo.setLayout(new javax.swing.BoxLayout(pnlBookingInfo, javax.swing.BoxLayout.Y_AXIS));

        lblDate.setText("Date");
        pnlBookingInfo.add(lblDate);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 51, 0));
        lblStatus.setText("Pending");
        pnlBookingInfo.add(lblStatus);

        pnlCenter.add(pnlBookingInfo, java.awt.BorderLayout.EAST);

        pnlInfo.setLayout(new javax.swing.BoxLayout(pnlInfo, javax.swing.BoxLayout.Y_AXIS));

        lblCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCustomerName.setText(" Customer Name");
        pnlInfo.add(lblCustomerName);

        lblHouseName.setForeground(new java.awt.Color(102, 102, 102));
        lblHouseName.setText(" House Name");
        pnlInfo.add(lblHouseName);

        lblCustomerId.setText(" Customer ID: -");
        pnlInfo.add(lblCustomerId);

        pnlCenter.add(pnlInfo, java.awt.BorderLayout.CENTER);

        add(pnlCenter, java.awt.BorderLayout.CENTER);

        pnlButtons.setOpaque(false);
        pnlButtons.setPreferredSize(new java.awt.Dimension(110, 80));
        pnlButtons.setLayout(new javax.swing.BoxLayout(pnlButtons, javax.swing.BoxLayout.Y_AXIS));

        btnAccept.setBackground(new java.awt.Color(43, 109, 80));
        btnAccept.setForeground(new java.awt.Color(255, 255, 255));
        btnAccept.setText("Accept");
        pnlButtons.add(btnAccept);

        btnReject.setForeground(new java.awt.Color(255, 51, 102));
        btnReject.setText("Reject");
        pnlButtons.add(btnReject);

        btnViewDetails.setForeground(new java.awt.Color(0, 0, 153));
        btnViewDetails.setText("View Details");
        pnlButtons.add(btnViewDetails);

        add(pnlButtons, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents
 public void setData(Booking b) {
        // customer & house info
        String cName = b.getCustomerName();
        lblCustomerName.setText(cName != null && !cName.isEmpty() ? cName : "Customer #" + b.getCustomerId());
        lblHouseName.setText(b.getHouseName() != null ? b.getHouseName() : "House");
        lblCustomerId.setText("Customer ID: " + b.getCustomerId());
 
        // date
        lblDate.setText(b.getBookingDate() != null ? b.getBookingDate() : "");
 
        // status
        String status = (b.getStatus() != null ? b.getStatus() : "pending").toLowerCase();
        switch (status) {
            case "confirmed" -> {
                lblStatus.setText("Confirmed");
                lblStatus.setForeground(new Color(34, 160, 70));
            }
            case "cancelled" -> {
                lblStatus.setText("Cancelled");
                lblStatus.setForeground(new Color(200, 50, 50));
            }
            default -> {
                lblStatus.setText("Pending");
                lblStatus.setForeground(new Color(210, 130, 0));
            }
        }
 
        // show Accept/Reject only for pending; View Details for others
        boolean isPending = "pending".equals(status);
        btnAccept.setVisible(isPending);
        btnReject.setVisible(isPending);
        btnViewDetails.setVisible(!isPending);
 
        // house image
        String imgPath = b.getFirstImage();
        if (imgPath != null && !imgPath.isBlank()) {
            loadImage(imgPath);
        }
    }
 
    private void loadImage(String path) {
        try {
            Image img = new ImageIcon(path)
                    .getImage().getScaledInstance(108, 80, Image.SCALE_SMOOTH);
            lblImage.setIcon(new ImageIcon(img));
            lblImage.setText("");
        } catch (Exception e) {
            lblImage.setText("No Image");
        }
    }
 
    /** Wire the Accept button from outside */
    public void setAcceptListener(java.awt.event.ActionListener l) {
        clearListeners(btnAccept);
        btnAccept.addActionListener(l);
    }
 
    /** Wire the Reject button from outside */
    public void setRejectListener(java.awt.event.ActionListener l) {
        clearListeners(btnReject);
        btnReject.addActionListener(l);
    }
 
    /** Wire the View Details button from outside */
    public void setViewDetailsListener(java.awt.event.ActionListener l) {
        clearListeners(btnViewDetails);
        btnViewDetails.addActionListener(l);
    }
 
    private void clearListeners(JButton btn) {
        for (var l : btn.getActionListeners()) btn.removeActionListener(l);
    
}
 private BookingActionListener actionListener;

public void setBookingActionListener(BookingActionListener listener) {
    this.actionListener = listener;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHouseName;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlBookingInfo;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlInfo;
    // End of variables declaration//GEN-END:variables
}
