package view;   // remove if not inside view folder
 
import controller.HouseController;
import javax.swing.*;
import model.House;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.io.File;
import util.SessionManager;
 
public class Owner_Add_House extends javax.swing.JFrame {
private List<String> selectedImages = new ArrayList<>();
    private HouseController houseController;
 
public Owner_Add_House(HouseController controller) {
    initComponents();
    this.houseController = controller;
 
    
 
 
}
    // NO CLOSING } HERE — class stays open for initComponents below
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel36 = new javax.swing.JLabel();
        GharSathi_Text = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        SearchHouse_Button = new javax.swing.JButton();
        Bookings_Button = new javax.swing.JButton();
        SavedHouse_Button = new javax.swing.JButton();
        Profile_Button = new javax.swing.JButton();
        Dashboard_Button = new javax.swing.JButton();
        Menuelogo_Button = new javax.swing.JButton();
        Username_Text = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Iconlogo_Button = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cmbBathrooms = new javax.swing.JComboBox<>();
        cmbHouseType = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        lblPreview1 = new javax.swing.JLabel();
        lblPreview2 = new javax.swing.JLabel();
        lblPreview3 = new javax.swing.JLabel();
        lblPreview4 = new javax.swing.JLabel();
        lblHouseName = new javax.swing.JLabel();
        cmbBedrooms = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbKitchens = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        wifiCheck1 = new javax.swing.JCheckBox();
        securityCheck = new javax.swing.JCheckBox();
        acCheck = new javax.swing.JCheckBox();
        balconyCheck = new javax.swing.JCheckBox();
        utilitiesCheck = new javax.swing.JCheckBox();
        parkingCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1536, 864));
        getContentPane().setLayout(null);

        jLabel36.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel36.setText("House Rental ");
        jLabel36.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel36);
        jLabel36.setBounds(110, 10, 250, 40);

        GharSathi_Text.setBackground(new java.awt.Color(243, 243, 243));
        GharSathi_Text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GharSathi_Text.setText("System");
        GharSathi_Text.setBorder(null);
        GharSathi_Text.addActionListener(this::GharSathi_TextActionPerformed);
        getContentPane().add(GharSathi_Text);
        GharSathi_Text.setBounds(110, 20, 220, 50);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled_-_Custom-removebg-preview.png"))); // NOI18N
        jLabel31.setText("jLabel31");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(-10, 0, 110, 90);

        SearchHouse_Button.setBackground(new java.awt.Color(43, 109, 80));
        SearchHouse_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SearchHouse_Button.setForeground(new java.awt.Color(255, 255, 255));
        SearchHouse_Button.setText("Add Houses");
        SearchHouse_Button.addActionListener(this::SearchHouse_ButtonActionPerformed);
        getContentPane().add(SearchHouse_Button);
        SearchHouse_Button.setBounds(450, 90, 260, 40);

        Bookings_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Bookings_Button.setText("Bookings");
        Bookings_Button.addActionListener(this::Bookings_ButtonActionPerformed);
        getContentPane().add(Bookings_Button);
        Bookings_Button.setBounds(710, 90, 260, 40);

        SavedHouse_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SavedHouse_Button.setText("Saved Houses");
        SavedHouse_Button.addActionListener(this::SavedHouse_ButtonActionPerformed);
        getContentPane().add(SavedHouse_Button);
        SavedHouse_Button.setBounds(970, 90, 260, 40);

        Profile_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Profile_Button.setText("Profile");
        Profile_Button.addActionListener(this::Profile_ButtonActionPerformed);
        getContentPane().add(Profile_Button);
        Profile_Button.setBounds(1230, 90, 260, 40);

        Dashboard_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Dashboard_Button.setText("Dashboard");
        Dashboard_Button.addActionListener(this::Dashboard_ButtonActionPerformed);
        getContentPane().add(Dashboard_Button);
        Dashboard_Button.setBounds(120, 90, 250, 40);

        Menuelogo_Button.setBackground(new java.awt.Color(243, 243, 243));
        Menuelogo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu.png"))); // NOI18N
        Menuelogo_Button.setBorder(null);
        Menuelogo_Button.addActionListener(this::Menuelogo_ButtonActionPerformed);
        getContentPane().add(Menuelogo_Button);
        Menuelogo_Button.setBounds(1490, 0, 50, 30);

        Username_Text.setBackground(new java.awt.Color(243, 243, 243));
        Username_Text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Username_Text.setText("Hello User");
        Username_Text.setBorder(null);
        Username_Text.setSelectedTextColor(new java.awt.Color(242, 242, 242));
        Username_Text.addActionListener(this::Username_TextActionPerformed);
        getContentPane().add(Username_Text);
        Username_Text.setBounds(1360, 30, 111, 20);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account_circle.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1310, 10, 40, 60);

        Iconlogo_Button.setBackground(new java.awt.Color(242, 242, 242));
        Iconlogo_Button.setForeground(new java.awt.Color(242, 242, 242));
        Iconlogo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bell_Icon.png"))); // NOI18N
        Iconlogo_Button.setBorder(null);
        Iconlogo_Button.addActionListener(this::Iconlogo_ButtonActionPerformed);
        getContentPane().add(Iconlogo_Button);
        Iconlogo_Button.setBounds(1220, 0, 80, 80);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel6.setText("Bathrooms");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(540, 130, 210, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setText("House Name");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(20, 50, 100, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel9.setText("Location");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(540, 50, 100, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel10.setText("Price ( Per Month )");
        jPanel7.add(jLabel10);
        jLabel10.setBounds(1050, 50, 210, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel11.setText("House Type");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(20, 130, 210, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel12.setText("Amenities ");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(1080, 240, 100, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel13.setText("Upload Images");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(10, 470, 160, 30);

        jButton1.setBackground(new java.awt.Color(43, 109, 80));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add House");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel7.add(jButton1);
        jButton1.setBounds(1300, 550, 130, 50);

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton2.setText("Reset");
        jPanel7.add(jButton2);
        jButton2.setBounds(1110, 550, 130, 50);

        jTextField1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField1.setText("Enter Price....(Nrs.)");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel7.add(jTextField1);
        jTextField1.setBounds(1050, 80, 380, 40);

        jTextField2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField2.setText("Enter house name...");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        jPanel7.add(jTextField2);
        jTextField2.setBounds(20, 80, 380, 40);

        jTextField3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField3.setText("Enter Location...");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jPanel7.add(jTextField3);
        jTextField3.setBounds(540, 80, 380, 40);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setName(""); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel7.add(jScrollPane1);
        jScrollPane1.setBounds(20, 310, 1030, 120);

        cmbBathrooms.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        cmbBathrooms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not selected", "1", "2", "3", "4", "5" }));
        cmbBathrooms.setSelectedIndex(0);
        cmbBathrooms.addActionListener(this::cmbBathroomsActionPerformed);
        jPanel7.add(cmbBathrooms);
        cmbBathrooms.setBounds(540, 160, 380, 40);

        cmbHouseType.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cmbHouseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modern Villa", "Residential", "Commercial", "Modern House", " " }));
        cmbHouseType.addActionListener(this::cmbHouseTypeActionPerformed);
        jPanel7.add(cmbHouseType);
        cmbHouseType.setBounds(20, 160, 380, 40);

        jButton3.setBackground(new java.awt.Color(229, 238, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 93, 191));
        jButton3.setText("Choose Files");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel7.add(jButton3);
        jButton3.setBounds(10, 510, 130, 30);

        lblPreview1.setBackground(new java.awt.Color(255, 255, 255));
        lblPreview1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreview1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.add(lblPreview1);
        lblPreview1.setBounds(210, 460, 180, 120);

        lblPreview2.setBackground(new java.awt.Color(255, 255, 255));
        lblPreview2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreview2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.add(lblPreview2);
        lblPreview2.setBounds(430, 460, 180, 120);

        lblPreview3.setBackground(new java.awt.Color(255, 255, 255));
        lblPreview3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreview3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.add(lblPreview3);
        lblPreview3.setBounds(650, 460, 180, 120);

        lblPreview4.setBackground(new java.awt.Color(255, 255, 255));
        lblPreview4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreview4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.add(lblPreview4);
        lblPreview4.setBounds(870, 460, 180, 120);

        lblHouseName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHouseName.setText("Add Property Details");
        jPanel7.add(lblHouseName);
        lblHouseName.setBounds(10, 10, 260, 30);

        cmbBedrooms.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        cmbBedrooms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not selected", "2BHK", "3BHK", "4BHK", "5BHK", "6BHK", "", "" }));
        jPanel7.add(cmbBedrooms);
        cmbBedrooms.setBounds(1050, 160, 380, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel7.setText("Bedrooms");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(1050, 130, 210, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel14.setText("Kitchen");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(20, 210, 210, 30);

        cmbKitchens.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        cmbKitchens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not selected", "1", "2", "3", "4", "5" }));
        cmbKitchens.addActionListener(this::cmbKitchensActionPerformed);
        jPanel7.add(cmbKitchens);
        cmbKitchens.setBounds(20, 240, 380, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel15.setText("Description");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(20, 280, 100, 30);

        jPanel1.setLayout(null);

        wifiCheck1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        wifiCheck1.setText("  WI-FI");
        wifiCheck1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        wifiCheck1.addActionListener(this::wifiCheck1ActionPerformed);
        jPanel1.add(wifiCheck1);
        wifiCheck1.setBounds(30, 20, 110, 40);

        securityCheck.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        securityCheck.setText("24/7 security");
        securityCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(securityCheck);
        securityCheck.setBounds(30, 120, 150, 40);

        acCheck.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        acCheck.setText("Air Condition");
        acCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        acCheck.addActionListener(this::acCheckActionPerformed);
        jPanel1.add(acCheck);
        acCheck.setBounds(180, 70, 150, 40);

        balconyCheck.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        balconyCheck.setText("Balcony");
        balconyCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(balconyCheck);
        balconyCheck.setBounds(180, 120, 120, 40);

        utilitiesCheck.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        utilitiesCheck.setText("Utilities");
        utilitiesCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        utilitiesCheck.addActionListener(this::utilitiesCheckActionPerformed);
        jPanel1.add(utilitiesCheck);
        utilitiesCheck.setBounds(30, 70, 120, 40);

        parkingCheck.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        parkingCheck.setText("  Parking");
        parkingCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(parkingCheck);
        parkingCheck.setBounds(180, 20, 110, 40);

        jPanel7.add(jPanel1);
        jPanel1.setBounds(1080, 280, 360, 210);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(50, 150, 1460, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GharSathi_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GharSathi_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GharSathi_TextActionPerformed

    private void SearchHouse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchHouse_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchHouse_ButtonActionPerformed

    private void Bookings_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bookings_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bookings_ButtonActionPerformed

    private void SavedHouse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavedHouse_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavedHouse_ButtonActionPerformed

    private void Profile_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_ButtonActionPerformed

    private void Dashboard_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dashboard_ButtonActionPerformed

    private void Menuelogo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menuelogo_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menuelogo_ButtonActionPerformed

    private void Username_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_TextActionPerformed

    private void Iconlogo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iconlogo_ButtonActionPerformed
  

    }//GEN-LAST:event_Iconlogo_ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
 
 
    if (jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in house name and location.");
        return;
    }
 
    House house = new House();
    house.setName(jTextField2.getText());
    house.setLocation(jTextField3.getText());
    house.setPrice(jTextField1.getText());
    house.setType((String) cmbHouseType.getSelectedItem());
    house.setBedrooms((String) cmbBedrooms.getSelectedItem());
    house.setBathrooms((String) cmbBathrooms.getSelectedItem());
    house.setKitchens((String) cmbKitchens.getSelectedItem());
    house.setDescription(jTextArea1.getText());
 
    List<String> amenities = new ArrayList<>();
    if (wifiCheck1.isSelected()) amenities.add("WI-FI");
    if (securityCheck.isSelected()) amenities.add("24/7 security");
    if (acCheck.isSelected()) amenities.add("Air Condition");
    if (balconyCheck.isSelected()) amenities.add("Balcony");
    if (utilitiesCheck.isSelected()) amenities.add("Utilities");
    if (parkingCheck.isSelected()) amenities.add("Parking");
    house.setAmenities(amenities);
 
    house.setImages(new ArrayList<>(selectedImages));
 
    // Guard: ensure user is logged in before accessing session
    if (SessionManager.getCurrentUser() == null) {
        JOptionPane.showMessageDialog(this, "Session expired. Please log in again.", "Session Error", JOptionPane.ERROR_MESSAGE);
        new view.Login().setVisible(true);
        this.dispose();
        return;
    }
    house.setOwnerId(SessionManager.getCurrentUser().getUserId());
 
    // Set approved so house shows in Dashboard, Search, and HouseDetails immediately
    house.setStatus("approved");
 
    houseController.addHouse(house);
 
    JOptionPane.showMessageDialog(this, "House added successfully!");
 
    // Reset form for next house (so owner can add multiple)
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField1.setText("");
    jTextArea1.setText("");
    cmbHouseType.setSelectedIndex(0);
    cmbBedrooms.setSelectedIndex(0);
    cmbBathrooms.setSelectedIndex(0);
    cmbKitchens.setSelectedIndex(0);
    wifiCheck1.setSelected(false);
    securityCheck.setSelected(false);
    acCheck.setSelected(false);
    balconyCheck.setSelected(false);
    utilitiesCheck.setSelected(false);
    parkingCheck.setSelected(false);
 
    selectedImages.clear();
    JLabel[] previews = {lblPreview1, lblPreview2, lblPreview3, lblPreview4};
    for (JLabel p : previews) p.setIcon(null);
 
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

   
    JFileChooser chooser = new JFileChooser();
    chooser.setMultiSelectionEnabled(true);
    chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "jpeg", "png"));
 
    int result = chooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File[] files = chooser.getSelectedFiles(); // multiple files
        selectedImages.clear();
 
        JLabel[] previews = {lblPreview1, lblPreview2, lblPreview3, lblPreview4};
        for (JLabel p : previews) p.setIcon(null);
 
        for (int i = 0; i < files.length && i < 4; i++) {
            selectedImages.add(files[i].getAbsolutePath());
            ImageIcon icon = new ImageIcon(files[i].getAbsolutePath());
            Image scaled = icon.getImage().getScaledInstance(180, 120, Image.SCALE_SMOOTH);
            previews[i].setIcon(new ImageIcon(scaled));
        }
    
    

    }
// TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbHouseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHouseTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHouseTypeActionPerformed

    private void cmbBathroomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBathroomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBathroomsActionPerformed

    private void cmbKitchensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKitchensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKitchensActionPerformed

    private void wifiCheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wifiCheck1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wifiCheck1ActionPerformed

    private void acCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acCheckActionPerformed

    private void utilitiesCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilitiesCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utilitiesCheckActionPerformed

    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
 
    java.awt.EventQueue.invokeLater(() -> {
        // Fetch a real user from DB for standalone testing so owner_id FK is valid
        if (util.SessionManager.getCurrentUser() == null) {
            try {
                database.MysqlConnector connector = new database.MysqlConnector();
                java.sql.Connection con = connector.openConnection();
                java.sql.PreparedStatement ps = con.prepareStatement(
                    "SELECT id, name FROM users ORDER BY id ASC LIMIT 1");
                java.sql.ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    model.User u = new model.User();
                    u.setUserId(rs.getInt("id"));
                    u.setUsername(rs.getString("name"));
                    util.SessionManager.setCurrentUser(u);
                } else {
                    // No users in DB — use id=0 (will fail FK if strict; good enough for testing)
                    model.User u = new model.User();
                    u.setUserId(0);
                    u.setUsername("test_owner");
                    util.SessionManager.setCurrentUser(u);
                }
                con.close();
            } catch (Exception ex) {
                ex.printStackTrace();
                model.User u = new model.User();
                u.setUserId(0);
                u.setUsername("test_owner");
                util.SessionManager.setCurrentUser(u);
            }
        }
        HouseController controller = new HouseController();
        new Owner_Add_House(controller).setVisible(true);
    });
 }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bookings_Button;
    private javax.swing.JButton Dashboard_Button;
    private javax.swing.JTextField GharSathi_Text;
    private javax.swing.JButton Iconlogo_Button;
    private javax.swing.JButton Menuelogo_Button;
    private javax.swing.JButton Profile_Button;
    private javax.swing.JButton SavedHouse_Button;
    private javax.swing.JButton SearchHouse_Button;
    private javax.swing.JTextField Username_Text;
    private javax.swing.JCheckBox acCheck;
    private javax.swing.JCheckBox balconyCheck;
    private javax.swing.JComboBox<String> cmbBathrooms;
    private javax.swing.JComboBox<String> cmbBedrooms;
    private javax.swing.JComboBox<String> cmbHouseType;
    private javax.swing.JComboBox<String> cmbKitchens;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblHouseName;
    private javax.swing.JLabel lblPreview1;
    private javax.swing.JLabel lblPreview2;
    private javax.swing.JLabel lblPreview3;
    private javax.swing.JLabel lblPreview4;
    private javax.swing.JCheckBox parkingCheck;
    private javax.swing.JCheckBox securityCheck;
    private javax.swing.JCheckBox utilitiesCheck;
    private javax.swing.JCheckBox wifiCheck1;
    // End of variables declaration//GEN-END:variables

}
