/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.UserController;
import dao.UserDAO;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import model.logindata;
import view.Login;

/**
 *
 * @author Safal
 */
public class OwnerRegistration extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OwnerRegistration.class.getName());

    /**
     * Creates new form Login
     */
    public OwnerRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegisterOwner = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnBackToLogin = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        TxtEmailORphoneNo = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnNext = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        TxtFullName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TxtConfirmPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1536, 864));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(250, 241, 224));
        jPanel1.setPreferredSize(new java.awt.Dimension(544, 864));
        jPanel1.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Register to rent your  ");
        jLabel22.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel22);
        jLabel22.setBounds(60, 650, 680, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Find your perfect home");
        jLabel5.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 280, 360, 40);

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel7.setText("House Rental ");
        jLabel7.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 160, 420, 60);

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel11.setText("           System");
        jLabel11.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(-150, 200, 880, 80);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("using GharSathi .    ");
        jLabel23.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel23);
        jLabel23.setBounds(60, 700, 180, 30);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("next perfect place to live ");
        jLabel24.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel24);
        jLabel24.setBounds(60, 680, 680, 30);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(53, 100, 166));
        jLabel25.setText("Need Help");
        jLabel25.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel25);
        jLabel25.setBounds(130, 750, 680, 30);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("issues ?");
        jLabel26.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel26);
        jLabel26.setBounds(60, 750, 680, 30);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(53, 100, 166));
        jLabel30.setText("Register,");
        jLabel30.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel1.add(jLabel30);
        jLabel30.setBounds(60, 600, 350, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HouseBg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 100, 540, 720);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled_-_Custom-removebg-preview.png"))); // NOI18N
        jLabel31.setText("jLabel31");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(180, 40, 120, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 544, 864);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Email/Phonenumber");
        jLabel3.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(650, 460, 220, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Signup ");
        jLabel6.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(650, 160, 880, 60);

        btnRegisterOwner.setBackground(new java.awt.Color(15, 75, 155));
        btnRegisterOwner.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegisterOwner.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterOwner.setText(" Register as Owner ");
        btnRegisterOwner.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegisterOwner.addActionListener(this::btnRegisterOwnerActionPerformed);
        getContentPane().add(btnRegisterOwner);
        btnRegisterOwner.setBounds(1130, 720, 300, 50);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel12.setText("WELCOME TO");
        jLabel12.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(650, 50, 880, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setText("Username");
        jLabel16.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel16);
        jLabel16.setBounds(650, 380, 290, 40);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel17.setText("Password");
        jLabel17.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel17);
        jLabel17.setBounds(650, 540, 330, 40);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(11, 75, 159));
        jLabel10.setText("House Rental System");
        jLabel10.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(650, 90, 880, 40);

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(11, 75, 159));
        jLabel20.setText("House Rental System");
        jLabel20.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(40, 50, 880, 40);

        btnBackToLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBackToLogin.setText("using GharSathi .     ");
        btnBackToLogin.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(btnBackToLogin);
        btnBackToLogin.setBounds(60, 740, 680, 20);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("using GharSathi .     ");
        jLabel28.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel28);
        jLabel28.setBounds(60, 740, 680, 20);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("using GharSathi .     ");
        jLabel29.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel29);
        jLabel29.setBounds(60, 740, 680, 20);

        TxtUsername.addActionListener(this::TxtUsernameActionPerformed);
        getContentPane().add(TxtUsername);
        TxtUsername.setBounds(650, 420, 650, 40);

        TxtEmailORphoneNo.addActionListener(this::TxtEmailORphoneNoActionPerformed);
        getContentPane().add(TxtEmailORphoneNo);
        TxtEmailORphoneNo.setBounds(650, 500, 650, 40);

        txtPassword.addActionListener(this::txtPasswordActionPerformed);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(650, 580, 650, 40);

        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnNext.setForeground(new java.awt.Color(51, 51, 51));
        btnNext.setText("Back to Login ");
        btnNext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNext.addActionListener(this::btnNextActionPerformed);
        getContentPane().add(btnNext);
        btnNext.setBounds(650, 720, 190, 50);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel18.setText("Full Name");
        jLabel18.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(650, 300, 290, 40);

        TxtFullName.addActionListener(this::TxtFullNameActionPerformed);
        getContentPane().add(TxtFullName);
        TxtFullName.setBounds(650, 340, 650, 40);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setText(" Confirm Password");
        jLabel19.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel19);
        jLabel19.setBounds(650, 620, 330, 40);

        TxtConfirmPassword.addActionListener(this::TxtConfirmPasswordActionPerformed);
        getContentPane().add(TxtConfirmPassword);
        TxtConfirmPassword.setBounds(650, 660, 650, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterOwnerActionPerformed
    String fullName = TxtFullName.getText().trim();
    String username = TxtUsername.getText().trim();
    String email    = TxtEmailORphoneNo.getText().trim();
    String password = new String(txtPassword.getPassword()).trim();
    String confirm  = new String(TxtConfirmPassword.getPassword()).trim();

    if (fullName.isEmpty() || username.isEmpty() || email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields!");
        return;
    }

    if (!password.equals(confirm)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match!");
        return;
    }

    UserDAO userDAO = new UserDAO();

    if (userDAO.emailExists(email)) {
        JOptionPane.showMessageDialog(this, "Email already registered!");
        return;
    }

    boolean success = userDAO.createOwner(fullName, username, email, password);

    if (success) {
        JOptionPane.showMessageDialog(this, "Owner account created! Please login.");
        new Login().setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Registration failed. Try again.");
    }

    }//GEN-LAST:event_btnRegisterOwnerActionPerformed

    private void TxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsernameActionPerformed

    private void TxtEmailORphoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmailORphoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmailORphoneNoActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

    new Login().setVisible(true);
    this.dispose();
 // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void TxtFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFullNameActionPerformed

    private void TxtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtConfirmPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OwnerRegistration().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TxtConfirmPassword;
    private javax.swing.JTextField TxtEmailORphoneNo;
    private javax.swing.JTextField TxtFullName;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JLabel btnBackToLogin;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnRegisterOwner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
