package view;

import controller.PasswordResetController;
import javax.swing.JOptionPane;

public class Reset_Password extends javax.swing.JFrame {

    private final String email;  // ← ADD

    public Reset_Password(String email) {  // ← ADD this constructor
        initComponents();
        this.email = email;
         setupEyeButtons();
    }
    private void setupEyeButtons() {

    // Eye button for New Password (jPasswordField2)
    javax.swing.JButton btnEye1 = new javax.swing.JButton("👁");
    btnEye1.setBounds(1290, 530, 50, 50);  // position next to jPasswordField2
    btnEye1.setFont(new java.awt.Font("Segoe UI", 0, 18));
    btnEye1.setFocusPainted(false);
    btnEye1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    getContentPane().add(btnEye1);

    // Eye button for Confirm Password (jPasswordField1)
    javax.swing.JButton btnEye2 = new javax.swing.JButton("👁");
    btnEye2.setBounds(1290, 610, 50, 50);  // position next to jPasswordField1
    btnEye2.setFont(new java.awt.Font("Segoe UI", 0, 18));
    btnEye2.setFocusPainted(false);
    btnEye2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    getContentPane().add(btnEye2);

    // Toggle show/hide for New Password
    btnEye1.addActionListener(e -> {
        if (txtNewPassword.getEchoChar() == 0) {
            txtNewPassword.setEchoChar('•');
            btnEye1.setText("👁");
        } else {
            txtNewPassword.setEchoChar((char) 0);
            btnEye1.setText("🙈");
        }
    });

    // Toggle show/hide for Confirm Password
    btnEye2.addActionListener(e -> {
        if (txtConfirmPassword.getEchoChar() == 0) {
            txtConfirmPassword.setEchoChar('•');
            btnEye2.setText("👁");
        } else {
            txtConfirmPassword.setEchoChar((char) 0);
            btnEye2.setText("🙈");
        }
    });

    // Make sure buttons appear on top
    getContentPane().setComponentZOrder(btnEye1, 0);
    getContentPane().setComponentZOrder(btnEye2, 0);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnResetPassword = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1536, 864));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(250, 241, 224));
        jPanel2.setPreferredSize(new java.awt.Dimension(544, 864));
        jPanel2.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setText("Set a new password");
        jLabel32.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel2.add(jLabel32);
        jLabel32.setBounds(60, 580, 680, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Find your perfect home");
        jLabel8.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(80, 250, 360, 40);

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel12.setText("House Rental ");
        jLabel12.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel2.add(jLabel12);
        jLabel12.setBounds(90, 140, 420, 60);

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel13.setText("           System");
        jLabel13.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel2.add(jLabel13);
        jLabel13.setBounds(-140, 170, 880, 80);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setText("account.    ");
        jLabel33.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel2.add(jLabel33);
        jLabel33.setBounds(60, 630, 180, 20);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setText("to secure your");
        jLabel34.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel2.add(jLabel34);
        jLabel34.setBounds(60, 610, 680, 20);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setText("is our priority");
        jLabel35.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel2.add(jLabel35);
        jLabel35.setBounds(190, 730, 680, 30);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(53, 100, 166));
        jLabel36.setText("Welcome Back,");
        jLabel36.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel2.add(jLabel36);
        jLabel36.setBounds(50, 540, 350, 30);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Rectangle 4_1.png"))); // NOI18N
        jLabel37.setText("jLabel31");
        jPanel2.add(jLabel37);
        jLabel37.setBounds(180, 40, 120, 120);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel38.setText("Your security ");
        jLabel38.setPreferredSize(new java.awt.Dimension(635, 244));
        jPanel2.add(jLabel38);
        jLabel38.setBounds(190, 720, 680, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/_7D47BD78-A051-46AC-9AA6-94ED3E6D9A1F_-removebg-preview 2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 40, 540, 720);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 544, 864);

        jlabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlabel11.setText("Re-enter your new password");
        jlabel11.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jlabel11);
        jlabel11.setBounds(660, 570, 330, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Enter and confirm your new password");
        jLabel4.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(660, 130, 880, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setText("Create a new password");
        jLabel6.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(650, 60, 880, 60);

        btnResetPassword.setBackground(new java.awt.Color(15, 75, 155));
        btnResetPassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnResetPassword.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPassword.setText("Reset Password");
        btnResetPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnResetPassword.addActionListener(this::btnResetPasswordActionPerformed);
        getContentPane().add(btnResetPassword);
        btnResetPassword.setBounds(700, 670, 580, 50);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(11, 75, 159));
        jLabel10.setText("RESET PASSWORD");
        jLabel10.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(650, 20, 880, 40);

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(11, 75, 159));
        jLabel18.setText("House Rental System");
        jLabel18.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(40, 60, 880, 40);

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(11, 75, 159));
        jLabel19.setText("House Rental System");
        jLabel19.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel19);
        jLabel19.setBounds(40, 30, 880, 40);

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(11, 75, 159));
        jLabel20.setText("House Rental System");
        jLabel20.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(40, 50, 880, 40);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("using GharSathi .     ");
        jLabel27.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel27);
        jLabel27.setBounds(60, 740, 680, 20);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("using GharSathi .     ");
        jLabel28.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel28);
        jLabel28.setBounds(60, 740, 680, 20);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("using GharSathi .     ");
        jLabel29.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel29);
        jLabel29.setBounds(60, 740, 680, 20);

        btnContinue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnContinue.setForeground(new java.awt.Color(51, 51, 51));
        btnContinue.setText("Continue");
        btnContinue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnContinue.addActionListener(this::btnContinueActionPerformed);
        getContentPane().add(btnContinue);
        btnContinue.setBounds(700, 730, 570, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ChatGPT Image M PM.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(760, 190, 470, 400);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel15.setText("Enter your new password");
        jLabel15.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(660, 490, 300, 40);

        txtConfirmPassword.addActionListener(this::txtConfirmPasswordActionPerformed);
        getContentPane().add(txtConfirmPassword);
        txtConfirmPassword.setBounds(660, 610, 680, 50);
        getContentPane().add(txtNewPassword);
        txtNewPassword.setBounds(660, 530, 680, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordActionPerformed


    String newPass = new String(txtNewPassword.getPassword()).trim();
    String confirmPass = new String(txtConfirmPassword.getPassword()).trim();

    PasswordResetController controller = new PasswordResetController();

    String error = controller.validatePassword(newPass, confirmPass);

    if (error != null) {
        JOptionPane.showMessageDialog(this, error);
        return;
    }

    boolean updated = controller.updatePassword(email, newPass);

    if (updated) {
        JOptionPane.showMessageDialog(this, "Password Reset Successful!");
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Failed to reset password!");
    }

    }//GEN-LAST:event_btnResetPasswordActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed


    Login login = new Login();
    login.setVisible(true);

    this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_btnContinueActionPerformed

    private void txtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
     new Reset_Password("test@gmail.com").setVisible(true);  // ← FIXED
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlabel11;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JPasswordField txtNewPassword;
    // End of variables declaration//GEN-END:variables
}
