package view;

import dao.HouseDAO;
import model.House;
import java.util.List;
import java.awt.*;
import javax.swing.*;

public class Searches_Customer extends javax.swing.JFrame {

    private HouseDAO houseDAO;

public Searches_Customer() {
    initComponents();
    houseDAO = new HouseDAO();

    // Change to GridLayout for reliable vertical scroll
    pnlHouseContainer.setLayout(new GridLayout(0, 4, 20, 20));   // 4 columns, auto rows

    scrollHouses.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    scrollHouses.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

    scrollHouses.setPreferredSize(new Dimension(1460, 590));

    SwingUtilities.invokeLater(this::loadHouses);
}

  private void loadHouses() {
    pnlHouseContainer.removeAll();

    List<House> houses = houseDAO.getAllHouses(); // or getApprovedHouses() later

    for (House house : houses) {
        HouseCardPanel1 card = new HouseCardPanel1(house);
        pnlHouseContainer.add(card);
    }

    // === IMPROVED VERTICAL SCROLL FIX ===
    // Force FlowLayout to wrap by setting width
    int viewportWidth = scrollHouses.getViewport().getWidth();
    if (viewportWidth <= 0) {
        viewportWidth = 1430; // safe fallback matching your scroll pane size
    }

    // This is the key line - make container width fixed so cards wrap to new rows
    pnlHouseContainer.setPreferredSize(new Dimension(
        viewportWidth - 40, 
        pnlHouseContainer.getPreferredSize().height + 100  // extra height to force scroll
    ));

    // Force refresh
    pnlHouseContainer.revalidate();
    pnlHouseContainer.repaint();
    scrollHouses.revalidate();
    scrollHouses.repaint();
    
    // Extra push after layout
    SwingUtilities.invokeLater(() -> {
        scrollHouses.revalidate();
        scrollHouses.repaint();
    });
}
    // NO CLOSING } HERE — class stays open for initComponents below
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel36 = new javax.swing.JLabel();
        SearchBar_Button = new javax.swing.JButton();
        GharSathi_Text = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        SearchHouse_Button = new javax.swing.JButton();
        Bookings_Button = new javax.swing.JButton();
        SavedHouse_Button = new javax.swing.JButton();
        Profile_Button = new javax.swing.JButton();
        Dashboard_Button = new javax.swing.JButton();
        Menuelogo_Button = new javax.swing.JButton();
        Username_Text = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Iconlogo_Button = new javax.swing.JButton();
        scrollHouses = new javax.swing.JScrollPane();
        pnlHouseContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1536, 864));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel36.setText("House Rental ");
        jLabel36.setPreferredSize(new java.awt.Dimension(635, 244));
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 250, 40));

        SearchBar_Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchBar_Button.setText("Search by Location,house name.......");
        SearchBar_Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        SearchBar_Button.addActionListener(this::SearchBar_ButtonActionPerformed);
        getContentPane().add(SearchBar_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 690, 40));

        GharSathi_Text.setBackground(new java.awt.Color(243, 243, 243));
        GharSathi_Text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GharSathi_Text.setText("System");
        GharSathi_Text.setBorder(null);
        GharSathi_Text.addActionListener(this::GharSathi_TextActionPerformed);
        getContentPane().add(GharSathi_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 220, 50));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GharSathi_Logo.png"))); // NOI18N
        jLabel31.setText("jLabel31");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 120, -1));

        SearchHouse_Button.setBackground(new java.awt.Color(15, 75, 155));
        SearchHouse_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SearchHouse_Button.setForeground(new java.awt.Color(255, 255, 255));
        SearchHouse_Button.setText("Search Houses");
        SearchHouse_Button.addActionListener(this::SearchHouse_ButtonActionPerformed);
        getContentPane().add(SearchHouse_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 260, 50));

        Bookings_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Bookings_Button.setText("Bookings");
        Bookings_Button.addActionListener(this::Bookings_ButtonActionPerformed);
        getContentPane().add(Bookings_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 260, 50));

        SavedHouse_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SavedHouse_Button.setText("Saved Houses");
        SavedHouse_Button.addActionListener(this::SavedHouse_ButtonActionPerformed);
        getContentPane().add(SavedHouse_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 260, 50));

        Profile_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Profile_Button.setText("Profile");
        Profile_Button.addActionListener(this::Profile_ButtonActionPerformed);
        getContentPane().add(Profile_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 110, 260, 50));

        Dashboard_Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Dashboard_Button.setText("Dashboard");
        Dashboard_Button.addActionListener(this::Dashboard_ButtonActionPerformed);
        getContentPane().add(Dashboard_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 250, 50));

        Menuelogo_Button.setBackground(new java.awt.Color(243, 243, 243));
        Menuelogo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu.png"))); // NOI18N
        Menuelogo_Button.setBorder(null);
        Menuelogo_Button.addActionListener(this::Menuelogo_ButtonActionPerformed);
        getContentPane().add(Menuelogo_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 0, 50, 30));

        Username_Text.setBackground(new java.awt.Color(243, 243, 243));
        Username_Text.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Username_Text.setText("Hello User");
        Username_Text.setBorder(null);
        Username_Text.setSelectedTextColor(new java.awt.Color(242, 242, 242));
        Username_Text.addActionListener(this::Username_TextActionPerformed);
        getContentPane().add(Username_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 50, -1, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/account_circle.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 30, 40, 60));

        Iconlogo_Button.setBackground(new java.awt.Color(242, 242, 242));
        Iconlogo_Button.setForeground(new java.awt.Color(242, 242, 242));
        Iconlogo_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bell_Icon.png"))); // NOI18N
        Iconlogo_Button.setBorder(null);
        Iconlogo_Button.addActionListener(this::Iconlogo_ButtonActionPerformed);
        getContentPane().add(Iconlogo_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 80, 80));

        pnlHouseContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20));
        scrollHouses.setViewportView(pnlHouseContainer);

        getContentPane().add(scrollHouses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 1460, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void GharSathi_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GharSathi_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GharSathi_TextActionPerformed

    private void SearchBar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBar_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBar_ButtonActionPerformed

    private void SearchHouse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchHouse_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchHouse_ButtonActionPerformed

    private void Bookings_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bookings_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bookings_ButtonActionPerformed

    private void SavedHouse_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavedHouse_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavedHouse_ButtonActionPerformed

    private void Profile_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Profile_ButtonActionPerformed

    private void Dashboard_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dashboard_ButtonActionPerformed

    private void Menuelogo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menuelogo_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menuelogo_ButtonActionPerformed

    private void Username_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_TextActionPerformed

    private void Iconlogo_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iconlogo_ButtonActionPerformed
  

    }//GEN-LAST:event_Iconlogo_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Searches_Customer().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bookings_Button;
    private javax.swing.JButton Dashboard_Button;
    private javax.swing.JTextField GharSathi_Text;
    private javax.swing.JButton Iconlogo_Button;
    private javax.swing.JButton Menuelogo_Button;
    private javax.swing.JButton Profile_Button;
    private javax.swing.JButton SavedHouse_Button;
    private javax.swing.JButton SearchBar_Button;
    private javax.swing.JButton SearchHouse_Button;
    private javax.swing.JTextField Username_Text;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel pnlHouseContainer;
    private javax.swing.JScrollPane scrollHouses;
    // End of variables declaration//GEN-END:variables



}