/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class owner_UI_report extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ghar_sathi.class.getName());

    
   
    public owner_UI_report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jProgressBar5 = new javax.swing.JProgressBar();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/owner_logo.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-10, 10, 60, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2.setText("System");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 30, 50, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("House Rental");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 10, 110, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search .png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(720, 20, 30, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("   Search by Location, house name.......");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 20, 490, 30);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 80, 30, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account_circle.png"))); // NOI18N
        jLabel16.setText("Hello, User");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(1370, 10, 100, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download 7.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(1480, 10, 22, 30);

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        jPanel1.add(jButton8);
        jButton8.setBounds(20, 80, 150, 30);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2026-06-09 220151.png"))); // NOI18N
        jPanel1.add(jButton9);
        jButton9.setBounds(720, 80, 150, 30);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1.png"))); // NOI18N
        jPanel1.add(jButton10);
        jButton10.setBounds(260, 80, 150, 30);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.png"))); // NOI18N
        jPanel1.add(jButton11);
        jButton11.setBounds(410, 80, 150, 30);

        jButton12.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saved.png"))); // NOI18N
        jButton12.setText("Saved Houses");
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton12.setIconTextGap(0);
        jPanel1.add(jButton12);
        jButton12.setBounds(560, 80, 160, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true));
        jPanel3.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wallet.png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(280, 40, 60, 60);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel11.setText("Total Earnings");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(30, 20, 110, 25);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setText("Rs  4,50,000");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(30, 50, 206, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(120, 180, 360, 150);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true));
        jPanel4.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(270, 40, 60, 60);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel12.setText("This Month");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(40, 20, 140, 25);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setText("Rs  50,000");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(40, 50, 206, 50);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(610, 180, 360, 150);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true));
        jPanel5.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N
        jPanel5.add(jLabel6);
        jLabel6.setBounds(280, 40, 60, 60);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel10.setText("This Year");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(50, 20, 140, 25);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("Rs  2,50,000");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(50, 50, 206, 50);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(1080, 180, 360, 150);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true));
        jPanel2.setLayout(null);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monthly earning'.png"))); // NOI18N
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 10, 250, 30);

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jProgressBar1.setMinimum(20);
        jProgressBar1.setValue(80);
        jProgressBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jProgressBar1);
        jProgressBar1.setBounds(170, 380, 240, 15);

        jProgressBar2.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar2.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jProgressBar2.setValue(50);
        jProgressBar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jProgressBar2);
        jProgressBar2.setBounds(170, 90, 240, 15);

        jProgressBar3.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar3.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jProgressBar3.setMinimum(20);
        jProgressBar3.setValue(80);
        jProgressBar3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jProgressBar3);
        jProgressBar3.setBounds(170, 160, 240, 15);

        jProgressBar4.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar4.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jProgressBar4.setMinimum(20);
        jProgressBar4.setValue(90);
        jProgressBar4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jProgressBar4);
        jProgressBar4.setBounds(170, 240, 240, 15);

        jProgressBar5.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar5.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jProgressBar5.setMinimum(20);
        jProgressBar5.setValue(48);
        jProgressBar5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(jProgressBar5);
        jProgressBar5.setBounds(170, 310, 240, 15);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("May");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(30, 370, 90, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Rs 35,000");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(450, 370, 90, 30);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("February");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(30, 160, 90, 30);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("March");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(30, 230, 90, 30);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("April");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(30, 300, 90, 30);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("January");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(30, 90, 90, 30);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Rs 25,000");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(450, 80, 90, 30);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Rs 35,000");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(450, 150, 90, 30);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Rs 45,000");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(450, 230, 90, 30);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Rs 30,000");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(450, 300, 90, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(50, 360, 580, 470);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 0), 1, true));
        jPanel6.setLayout(null);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/23444.png"))); // NOI18N
        jPanel6.add(jLabel18);
        jLabel18.setBounds(10, 10, 220, 40);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chart.png"))); // NOI18N
        jPanel6.add(jLabel30);
        jLabel30.setBounds(50, 70, 630, 380);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(740, 360, 760, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1540, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ghar_sathi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    // End of variables declaration//GEN-END:variables
}
