

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
import database.DBConnection;
import java.io.File;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

public class owner_UI_Upload extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ghar_sathi.class.getName());
    private File[] selectedImages;
    
   
    public owner_UI_Upload() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/owner_logo.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-10, 10, 60, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel2.setText("System");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 30, 50, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("House Rental");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 10, 110, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search .png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(720, 20, 30, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("   Search by Location, house name.......");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 20, 490, 30);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 80, 30, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account_circle.png"))); // NOI18N
        jLabel16.setText("Hello, User");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(1370, 10, 100, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download 7.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(1480, 10, 22, 30);

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png"))); // NOI18N
        jPanel1.add(jButton8);
        jButton8.setBounds(20, 90, 150, 30);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2026-06-09 220151.png"))); // NOI18N
        jPanel1.add(jButton9);
        jButton9.setBounds(950, 90, 150, 30);

        jButton10.setBackground(new java.awt.Color(247, 247, 247));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/building.png"))); // NOI18N
        jButton10.setText("Add Houses");
        jPanel1.add(jButton10);
        jButton10.setBounds(330, 90, 160, 30);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/report.png"))); // NOI18N
        jPanel1.add(jButton11);
        jButton11.setBounds(640, 90, 150, 30);

        jButton12.setBackground(new java.awt.Color(247, 247, 247));
        jButton12.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saved.png"))); // NOI18N
        jButton12.setText("Saved Houses");
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton12.setIconTextGap(0);
        jPanel1.add(jButton12);
        jButton12.setBounds(790, 90, 160, 30);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b1.png"))); // NOI18N
        jPanel1.add(jButton13);
        jButton13.setBounds(490, 90, 150, 30);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel6.setText("Bedrooms");
        jPanel7.add(jLabel6);
        jLabel6.setBounds(460, 260, 170, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setText("House Name");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(20, 20, 170, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel9.setText("Location");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(30, 140, 170, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel10.setText("Price ( Per Month )");
        jPanel7.add(jLabel10);
        jLabel10.setBounds(450, 140, 170, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel11.setText("House Type");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(440, 20, 170, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel12.setText("Description");
        jPanel7.add(jLabel12);
        jLabel12.setBounds(30, 260, 170, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel13.setText("Upload Images");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(30, 420, 170, 30);

        jButton1.setBackground(new java.awt.Color(0, 114, 20));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add House");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel7.add(jButton1);
        jButton1.setBounds(860, 650, 220, 40);

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton2.setText("Reset");
        jPanel7.add(jButton2);
        jButton2.setBounds(640, 650, 220, 40);

        jTextField1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField1.setText("Enter Price....(Nrs.)");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel7.add(jTextField1);
        jTextField1.setBounds(450, 180, 340, 40);

        jTextField2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField2.setText("Enter house name...");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        jPanel7.add(jTextField2);
        jTextField2.setBounds(30, 60, 340, 40);

        jTextField3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTextField3.setText("Enter Location...");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jPanel7.add(jTextField3);
        jTextField3.setBounds(30, 180, 340, 40);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setName(""); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel7.add(jScrollPane1);
        jScrollPane1.setBounds(30, 300, 340, 90);

        jComboBox1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2BHK", "3BHK", "4BHK", "5BHK", "6BHK", " ", " " }));
        jPanel7.add(jComboBox1);
        jComboBox1.setBounds(450, 300, 340, 40);

        jComboBox2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modern Villa", "Residential", "Commercial", "Modern House", " " }));
        jPanel7.add(jComboBox2);
        jComboBox2.setBounds(440, 60, 340, 40);

        jButton3.setBackground(new java.awt.Color(229, 238, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 93, 191));
        jButton3.setText("Choose Files");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel7.add(jButton3);
        jButton3.setBounds(30, 460, 140, 30);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add image.png"))); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.add(jLabel17);
        jLabel17.setBounds(870, 460, 210, 160);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add image.png"))); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.add(jLabel18);
        jLabel18.setBounds(210, 460, 210, 160);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add image.png"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.add(jLabel19);
        jLabel19.setBounds(430, 460, 210, 160);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add image.png"))); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.add(jLabel20);
        jLabel20.setBounds(650, 460, 210, 160);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel7.add(jLabel21);
        jLabel21.setBounds(690, 310, 430, 620);

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel29.setText("Management");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(830, 60, 290, 70);

        jLabel30.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel30.setText("Property");
        jPanel7.add(jLabel30);
        jLabel30.setBounds(900, 30, 160, 50);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("List a new prperty into the Ghar Sathi rental place");
        jPanel7.add(jLabel22);
        jLabel22.setBounds(710, 120, 390, 25);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(420, 140, 1120, 730);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghar.png"))); // NOI18N
        jPanel2.add(jLabel14);
        jLabel14.setBounds(0, 0, 400, 544);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel25.setText("jLabel25");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(-20, 360, 630, 470);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 180, 630, 690);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jPanel1.add(jLabel28);
        jLabel28.setBounds(1120, 0, 420, 216);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1540, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    
   
    JFileChooser chooser = new JFileChooser();
    

    // Allow multiple image selection
    chooser.setMultiSelectionEnabled(true);

    // Only image files
    FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Image Files", "jpg", "jpeg", "png", "gif");

    chooser.setFileFilter(filter);

    int result = chooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {

        File[] files = chooser.getSelectedFiles();
        selectedImages = files;

        // Store your labels in an array
        JLabel[] labels = {
            jLabel18,
            jLabel19,
            jLabel20,
            jLabel17
        };

        // Display each selected image in a different label
        for (int i = 0; i < files.length && i < labels.length; i++) {

            ImageIcon icon = new ImageIcon(files[i].getAbsolutePath());

            Image img = icon.getImage().getScaledInstance(
                    labels[i].getWidth(),
                    labels[i].getHeight(),
                    Image.SCALE_SMOOTH);

            labels[i].setIcon(new ImageIcon(img));
        }
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn = (Connection) DBConnection.getConnection();

String sql =
"INSERT INTO houses " +
"(house_name,house_type,location,price,bedrooms,description,image1,image2,image3,image4) " +
"VALUES (?,?,?,?,?,?,?,?,?,?)";

PreparedStatement ps = conn.prepareStatement(sql);

ps.setString(1, jTextField2.getText());

ps.setString(2, jComboBox2.getSelectedItem().toString());

ps.setString(3, jTextField3.getText());

ps.setDouble(4,
        Double.parseDouble(jTextField1.getText()));

ps.setString(5,
        jComboBox1.getSelectedItem().toString());

ps.setString(6,
        jTextArea1.getText());

String img1 = null;
String img2 = null;
String img3 = null;
String img4 = null;

if (selectedImages != null) {

    if (selectedImages.length > 0)
        img1 = selectedImages[0].getAbsolutePath();

    if (selectedImages.length > 1)
        img2 = selectedImages[1].getAbsolutePath();

    if (selectedImages.length > 2)
        img3 = selectedImages[2].getAbsolutePath();

    if (selectedImages.length > 3)
        img4 = selectedImages[3].getAbsolutePath();
}

ps.setString(7, img1);
ps.setString(8, img2);
ps.setString(9, img3);
ps.setString(10, img4);

ps.executeUpdate();

javax.swing.JOptionPane.showMessageDialog(
        null,
        "House Added Successfully");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new owner_UI_Upload().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
